### ISSUE TITLE
NWNX_Chat Skip

### ISSUE THREAD

**Issue by zunath** [nwnxee/unified#100]
It looks like if you call SkipMessage, and later call SendMessage within the same event, it actually skips both messages instead of just the original.

In 1.69, you could do a SkipMessage and then immediately send a different message and have the new one go through.

I ran into this when I tried to do SkipMessage on a party chat message, and then sent a message by tell from an NPC to a player.

**Comment by Dorakhan** [comment]
I can confirm the same issue.

**Comment by Liareth** [comment]
As a workaround, you can just `DelayCommand(0.0)` it.

**Comment by Dorakhan** [comment]
DelayCommand(0.0) is having rather unpredictable results.... I wish I could better document it.

**Comment by Dorakhan** [comment]
Never-ye-mind. I was wrapping the wrong function like an idiot.
