### ISSUE TITLE
[Request] NWNX_Tweaks: allow armor with max. DEX bonus 0

### ISSUE THREAD

**Issue by Arvirago** [nwnxee/unified#1047]
Add an option to NWNX_Tweaks to allow defining an armor with a max. DEX bonus of 0, hooking the CNWSCreatureStats__GetDEXMod function.
Right now NWN won't allow anything under 1.
I tried to do it but my skills are not enough.
This is what I came up to:
```c
#include "Tweaks/FixArmorDexBonusUnderOne.hpp"

#include "Services/Hooks/Hooks.hpp"
#include "Utils.hpp"

#include "API/CNWRules.hpp"
#include "API/CNWSCreature.hpp"
#include "API/CNWSCreatureStats.hpp"
#include "API/CNWSInventory.hpp"
#include "API/CNWSItem.hpp"
#include "API/CTwoDimArrays.hpp"
#include "API/Functions.hpp"

namespace Tweaks {

using namespace NWNXLib;
using namespace NWNXLib::API;

FixArmorDexBonusUnderOne::FixArmorDexBonusUnderOne(Services::HooksProxy* hooker)
{
    hooker->RequestExclusiveHook<Functions::_ZN17CNWSCreatureStats9GetDEXModEi>
                                    (&CNWSCreatureStats__GetDEXMod_hook);
}

char FixArmorDexBonusUnderOne::CNWSCreatureStats__GetDEXMod_hook(CNWSCreature *pThis, int32_t bArmorDexCap)
{
    char nDexAC = pThis->m_pStats->m_nDexterityModifier;

    if (bArmorDexCap)
    {
        auto pArmor = pThis->m_pInventory->GetItemInSlot(Constants::EquipmentSlot::Chest);
        int nTempValue = 0;
        if (pArmor && (nTempValue = pArmor->ComputeArmorClass()) > 0)
        {
            Globals::Rules()->m_p2DArrays->m_pArmorTable->GetINTEntry(nTempValue, CExoString("DEXBONUS"), &nTempValue);
            if (nTempValue < nDexAC)
                nDexAC = static_cast<char>(nTempValue);
        }
    }

    return nDexAC;
}

}
```

**Comment by plenarius** [comment]
This looks like it should work... are you not seeing the results you want or are you not understanding how the tweak should be set up from a configuration stand point?

**Comment by Arvirago** [comment]
It failed to compile, and I was unable to fix it

**Comment by plenarius** [comment]
Here's some help to see if you can get it working.

Add to Tweaks/Tweaks.cpp:
Line 22
```c
#include "Tweaks/FixArmorDexBonusUnderOne.hpp"
```
Line 164
```c
    if (GetServices()->m_config->Get<bool>("FIX_ARMOR_DEX_BONUS_UNDER_ONE", false))
    {
        LOG_INFO("Allowing a dex bonus of 0 on armor");
        m_FixArmorDexBonusUnderOne = std::make_unique<FixArmorDexBonusUnderOne>(GetServices()->m_hooks.get());
    }
```
Add to Tweaks/Tweaks.hpp:
Line 28
```c
class FixArmorDexBonusUnderOne;
```
Line 57
```c
    std::unique_ptr<FixArmorDexBonusUnderOne> m_FixArmorDexBonusUnderOne;
```
Add to Tweaks/CMakeLists.txt:
Line 23
```c
    "Tweaks/FixArmorDexBonusUnderOne.cpp"
```
Add Tweaks/Tweaks/FixArmorDexBonusUnderOne.hpp
```c
#pragma once

#include "Common.hpp"
#include "Services/Hooks/Hooks.hpp"

namespace Tweaks {

class FixArmorDexBonusUnderOne
{
public:
    FixArmorDexBonusUnderOne(NWNXLib::Services::HooksProxy* hooker);

private:
    static uint8_t CNWSCreatureStats__GetDEXMod_hook(CNWSCreature *pThis, int32_t bArmorDexCap);
};

}
```
Change the `char` in your FixArmorDexBonusUnderOne.cpp to `uint8_t`

**Comment by plenarius** [comment]
Did you get this to work as you'd hope? Did you want me to commit this to the main repository or were you planning to? It may be of use to someone else.

**Comment by Arvirago** [comment]
Sorry I haven't had time to try. I have to set up my working environment again and then try to compile. I will report when I'm done.
I'm afraid I'm not very good using github and c++

**Comment by Arvirago** [comment]
The changes you proposed in Tweaks.cpp, Tweaks.hpp and CMakeLists.txt I already had them, I didn't want to copy everything here.
In the hpp I also had
`#include` "API/Types.hpp"
I did the change from char to uint8_t.
I suppose I must change also the "char nDexAC" for "int nDexAC"
I will try now
