### ISSUE TITLE
NWNX_Events: on cast interrupt (request)

### ISSUE THREAD

**Issue by burmashave** [nwnxee/unified#1077]
I've implemented a mana-based spellcasting system where spells are restored after each casting as long as there is enough mana remaining. My one problem is that I have no way of detecting when a spell gets interrupted.  Any chance something like that could be added to the events plugin?

**Comment by plenarius** [comment]
Hi, I took a quick look at this and there doesn't at first glance look to be an easy way. The best I could come up with is hacking the Effects events to allow for your one case of a Visual Effect event. In the case of the spell failed effect, the visual effects are either 292 or 293. So this would require something like this in the EffectEvents.cpp and then for you to use the effects event and check for the Visual effect type and the int[0] to be either 292 or 293

```diff
diff --git a/Plugins/Events/Events/EffectEvents.cpp b/Plugins/Events/Events/EffectEvents.cpp
index e04c64c185..b8b0708885 100644
--- a/Plugins/Events/Events/EffectEvents.cpp
+++ b/Plugins/Events/Events/EffectEvents.cpp
@@ -33,7 +33,6 @@ void EffectEvents::HandleEffectHook(const std::string& event, bool before, CNWSO
     switch (pEffect->m_nType)
     {
         case EffectTrueType::Icon:
-        case EffectTrueType::VisualEffect:
         case EffectTrueType::Link:
         case EffectTrueType::ItemProperty:
         case EffectTrueType::Beam:
@@ -43,6 +42,10 @@ void EffectEvents::HandleEffectHook(const std::string& event, bool before, CNWSO
             break;
     }
 
+    if (pEffect->m_nType == EffectTrueType::VisualEffect &&
+       (!pEffect->m_nNumIntegers || (pEffect->m_nParamInteger[0] != 292 && pEffect->m_nParamInteger[0] != 293)))
+            return;
+
     Events::PushEventData("UNIQUE_ID", std::to_string(pEffect->m_nID));
     Events::PushEventData("CREATOR", Utils::ObjectIDToString(pEffect->m_oidCreator));
     Events::PushEventData("TYPE", std::to_string(pEffect->m_nType));
```

event_effects.nss
```c
if (NWNX_Events_GetCurrentEvent() == "NWNX_ON_EFFECT_APPLIED_BEFORE")
{
    if (NWNX_Events_GetEventData("TYPE") == "30" && (NWNX_Events_GetEventData("nParam0") == "292" || NWNX_Events_GetEventData("nParam0") == 293))
    {
     // spell interrupted
    }
}
```

I'm not sure if there are greater ramifications to allow this Visual Effect to use the events plugin though but just getting my info down here in case anyone sees something easier to do.

**Comment by burmashave** [comment]
Thanks for at least looking into it, I really appreciate it. If it can't be done through nwnx_events I'll have to hack up some other detection routine, but I wanted to check here first because this plugin has been such a lifesaver.

**Comment by plenarius** [comment]
I suppose we could just hook `CNWSEffectListHandler::EffectApplied` again since it's a shared hook and give this specific case its own special event but seeing if anyone else has any better ideas looking at how Spell Interruption takes place.
