### ISSUE TITLE
NWNX LevelDown Bug 

### ISSUE THREAD

**Issue by Valbor99** [nwnxee/unified#1083]
D [19:38:36] [NWNX_Core] [Events.hpp:101] Pushing argument '1'. Event 'LevelDown', Plugin: 'NWNX_Creature'.
D [19:38:36] [NWNX_Core] [Events.hpp:101] Pushing argument '97d'. Event 'LevelDown', Plugin: 'NWNX_Creature'.
D [19:38:36] [NWNXLib] [Events.cpp:42] Calling event handler. Event 'LevelDown', Plugin: 'NWNX_Creature'.
D [19:38:37] [NWNX_Core] [Events.hpp:101] Pushing argument '1'. Event 'LevelDown', Plugin: 'NWNX_Creature'.
D [19:38:37] [NWNX_Core] [Events.hpp:101] Pushing argument '97d'. Event 'LevelDown', Plugin: 'NWNX_Creature'.
D [19:38:37] [NWNXLib] [Events.cpp:42] Calling event handler. Event 'LevelDown', Plugin: 'NWNX_Creature'.
D [19:38:37] [NWNX_Core] [Events.hpp:101] Pushing argument '1'. Event 'LevelDown', Plugin: 'NWNX_Creature'.
D [19:38:37] [NWNX_Core] [Events.hpp:101] Pushing argument '97d'. Event 'LevelDown', Plugin: 'NWNX_Creature'.
D [19:38:37] [NWNXLib] [Events.cpp:42] Calling event handler. Event 'LevelDown', Plugin: 'NWNX_Creature'.
 NWNX Signal Handler:
==============================================================
 NWNX has crashed. Fatal error: Segmentation fault (11).
 Please file a bug at https://github.com/nwnxee/unified/issues
==============================================================

  Backtrace:
    /home/vetal/unified/Binaries/NWNX_Core.so(_ZN7NWNXLib8Platform5Debug13GetStackTraceB5cxx11Eh+0x49) [0x7fbcaf349c29]
    /home/vetal/unified/Binaries/NWNX_Core.so(nwnx_signal_handler+0x92) [0x7fbcaf2aa732]
    /lib/x86_64-linux-gnu/libc.so.6(+0x3efd0) [0x7fbcade8efd0]
    ./nwserver-linux(_ZN8CNWClass12IsNormalFeatEt+0x13) [0x7fbcb01e0863]
    ./nwserver-linux(_ZN17CNWSCreatureStats19SetNormalBonusFlagsEtRiS0_+0x7d) [0x7fbcafc2acad]
    ./nwserver-linux(_ZN17CNWSCreatureStats13CanChooseFeatEthhP13CExoArrayListItE+0x132) [0x7fbcafc3eac2]
    ./nwserver-linux(_ZN17CNWSCreatureStats16LevelUpAutomaticEhih+0x125f) [0x7fbcafc4e2cf]
    ./nwserver-linux(_ZN25CNWVirtualMachineCommands29ExecuteCommandLevelUpHenchmanEii+0xe6) [0x7fbcafd9e046]
    ./nwserver-linux(_ZN15CVirtualMachine11ExecuteCodeEPiSt10shared_ptrI9DataBlockEP31CVirtualMachineDebuggingContext+0x10dd) [0x7fbcb01d1efd]
    ./nwserver-linux(_ZN15CVirtualMachine13RunScriptFileEi+0xa9) [0x7fbcb01d3689]
    ./nwserver-linux(_ZN15CVirtualMachine9RunScriptEP10CExoStringji+0x12f) [0x7fbcb01d44bf]
    ./nwserver-linux(_ZN25CNWVirtualMachineCommands27ExecuteCommandExecuteScriptEii+0xa8) [0x7fbcafd73d88]
    ./nwserver-linux(_ZN15CVirtualMachine11ExecuteCodeEPiSt10shared_ptrI9DataBlockEP31CVirtualMachineDebuggingContext+0x10dd) [0x7fbcb01d1efd]
    ./nwserver-linux(_ZN15CVirtualMachine13RunScriptFileEi+0xa9) [0x7fbcb01d3689]
    ./nwserver-linux(_ZN15CVirtualMachine18RunScriptSituationEPvji+0xd5) [0x7fbcb01d38d5]
    ./nwserver-linux(_ZN10CNWSModule12EventHandlerEjjPvjj+0x142) [0x7fbcafc7a662]
    ./nwserver-linux(_ZN15CServerAIMaster11UpdateStateEv+0x4e7) [0x7fbcafcf18f7]
    ./nwserver-linux(_ZN21CServerExoAppInternal8MainLoopEv+0x1aa) [0x7fbcafd0431a]
    /home/vetal/unified/Binaries/NWNX_Core.so(_ZN7NWNXLib8Services9HooksImpl23HookLandingHolderShared11HookLandingILm3162480EiP21CServerExoAppInternalJEEET0_T1_DpT2_+0x52) [0x7fbcaf2b0f82]
    ./nwserver-linux(<UNKNOWN>) [0x7fbcafadb5d5]
Please go to https://beamdog.atlassian.net/servicedesk/ and report this crash to the Neverwinter Nights bug reporter.

This happens after i removed all 39 levels with NWNX_Creature_LevelDown(oHench, 1); from my henchman and then tried up his level-up from LevelUpHenchman() to max in another class, i don't know why, but sometimes the error doesn't happen the first time.

**Comment by plenarius** [comment]
I tried repeating this but couldn't. Can you give us a bit more detail please?
How was the creature's levels given in the first place? Just assigned through the toolset? Was the levelup wizard used?
Are they a multiclass or just the one class?

**Comment by Valbor99** [comment]
I disconnected my HAKs from the module and checked the same systems, no errors were found, apparently there are some conflicts with 2da tables to classes on my side, sorry for what i bothered you in vain.

**Comment by plenarius** [comment]
Well, we would like to prevent crashes even when users have odd things taking place in their 2da files, so if you feel like sharing a bit more of what you think the culprit is with your classes setup, you can!

**Comment by Valbor99** [comment]
I will have to postpone this work for a while, but later I will deal with this problem, and if i find the reason, i will report here.

**Comment by Valbor99** [comment]
Well, yesterday i decided to deal with this problem of the Re-Level for my henchman, strange but i could not reproduce that error, it after updating the plugins, it no longer occurs, and i have no idea what caused it then, as i wrote, it did not always server crush. Excuse for troubling :)
