### ISSUE TITLE
NWNX Race and removing effects.

### ISSUE THREAD

**Issue by Morderon** [nwnxee/unified#1095]
After a server has been up for a while effects applied through NWNX_Race stop being removed; and therefore stack with prior applications.

The plugin works correctly, with proper removal, immediately after server start up.

**Comment by plenarius** [comment]
Are you up to date with latest source? I thought I corrected this with this bug fix https://github.com/nwnxee/unified/commit/f174e824f2b922d69fc6e18bf74f8229ea075767

**Comment by Morderon** [comment]
Yes, merged in and updated NWNX.,Race.so just a couple of hours ago.

**Comment by plenarius** [comment]
Hmm I wonder then if this is the exact same issue as Feat that I just corrected. The Race plugin removes effects before the TURD effects are applied, and they're nonexistent at that point. https://github.com/nwnxee/unified/commit/9dd6c9d96a46b65e487cdf5bb64ee2ce0832dbbb

**Comment by plenarius** [comment]
Turns out this issue was indeed related to https://github.com/nwnxee/unified/commit/f174e824f2b922d69fc6e18bf74f8229ea075767
