### ISSUE TITLE
PC Skill Points function request

### ISSUE THREAD

**Issue by ELadner** [nwnxee/unified#110]
GetPCSkillPoints and SetPCSkillPoints 

(originally from nwnx_funcs).

**Comment by ELadner** [comment]
...unless this is the same as (Get|Set)SkillPointsRemaining

**Comment by mtijanic** [comment]
Yeah, I think these are the same thing.

**Comment by ELadner** [comment]
Gotcha..  the "Remaining" threw me.

**Comment by mtijanic** [comment]
Remaining as in "unspent".
