### ISSUE TITLE
Add Get/Set/Remove Known Feat

### ISSUE THREAD

**Issue by ELadner** [nwnxee/unified#111]
Probably in nwnx_creature.  Originally in nwnx_funcs

**Comment by ELadner** [comment]
or is NWNX_Creature_(Get|Set|Remove)Feat the EE version...

**Comment by mtijanic** [comment]
The old interface wasn't really safe. You have Get, Add and Remove now, so you can't just swap out an existing feat (or write past the bounds). You can make a 1:1 translation in nwscript.

**Comment by ELadner** [comment]
Cool..  Thanks.
