### ISSUE TITLE
REQUEST - Event Plugin - Add events NWNX_ON_JOURNAL_OPEN and NWNX_ON_JOURNAL_CLOSE

### ISSUE THREAD

**Issue by Chimerik** [nwnxee/unified#1121]
Hi guys,

Would it be possible to add events NWNX_ON_JOURNAL_OPEN and NWNX_ON_JOURNAL_CLOSE to the event plugin?
It would allow to update displayed data just when the player is trying to read it.

Thanks for your help,
Chim

**Comment by Daztek** [comment]
I was going to do this, I shall do so.
