### ISSUE TITLE
Bug: NWNX_Creature_SetSpecialAbility

### ISSUE THREAD

**Issue by Morderon** [nwnxee/unified#114]
Fails to do anything, most notable return the index/spell to a ready state.

**Comment by mtijanic** [comment]
Thanks Mord! Do you have something handy that I can test with?

**Comment by mtijanic** [comment]
Likewise. Closing.

**Comment by Morderon** [comment]
Oh yeah sorry i fixed it a while ago. I just didn't close it out.

**Comment by Morderon** [comment]
And if your curious what it was it was alright on the nwnx side.

The nwscript just wasn't pushing all the required arguments.
