### ISSUE TITLE
does not upload the server  version .20

### ISSUE THREAD

**Issue by FronteraOmega** [nwnxee/unified#1183]
Have a problem to lunch the server and not i know fix it.

Starting NWNX 8193.20 [3009fc867a]
=========================================
  Base address is:   0x0000556265840fc0
  g_pExoBase is:     0x0000556266437620
  Corrected 7593 ASLR addresses
=========================================
Neverwinter Nights Server
Build: 8193.20 []
Copyright BioWare Corp 1998-2004
Registering crash signal handlers.

Server: Loading...
N [01:36:49] [NWNX_Core] [NWNXCore.cpp:604] Loading NWNX.
ASSERTION FAILURE
  Summary: (rv == FUNCHOOK_ERROR_SUCCESS) failed at (/root/nwnx/NWNXLib/Hooking/FunctionHook.cpp:14)
  Backtrace:
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib8Platform5Debug13GetStackTraceB5cxx11Eh+0x49) [0x7f664156d8e9]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib6Assert4FailEPKcS2_iS2_+0x9d) [0x7f66414fbd4d]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib7Hooking12FunctionHookC2Emm+0x7a) [0x7f6641524a0a]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib8Services5Hooks20RequestExclusiveHookILm3830256EiJP25CNWVirtualMachineCommandsiiEEENS1_17RegistrationTokenEPFT0_DpT1_E+0xe2) [0x7f66414dca62]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN4Core8NWNXCore17InitialSetupHooksEv+0x5c) [0x7f66414d0d3c]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN4Core8NWNXCore19CreateServerHandlerEP11CAppManager+0x7a3) [0x7f66414d3933]
    ./nwserver-linux(<UNKNOWN>) [0x55626591b817]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6640079bf7]
    ./nwserver-linux(_start+0x2a) [0x55626591fe4a]
ASSERTION FAILURE
  Summary: (rv == FUNCHOOK_ERROR_SUCCESS) failed at (/root/nwnx/NWNXLib/Hooking/FunctionHook.cpp:14)
  Backtrace:
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib8Platform5Debug13GetStackTraceB5cxx11Eh+0x49) [0x7f664156d8e9]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib6Assert4FailEPKcS2_iS2_+0x9d) [0x7f66414fbd4d]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib7Hooking12FunctionHookC2Emm+0x7a) [0x7f6641524a0a]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib8Services5Hooks20RequestExclusiveHookILm3657680EiJP25CNWVirtualMachineCommandsiiEEENS1_17RegistrationTokenEPFT0_DpT1_E+0xe2) [0x7f66414dcde2]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN4Core8NWNXCore17InitialSetupHooksEv+0x82) [0x7f66414d0d62]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN4Core8NWNXCore19CreateServerHandlerEP11CAppManager+0x7a3) [0x7f66414d3933]
    ./nwserver-linux(<UNKNOWN>) [0x55626591b817]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6640079bf7]
    ./nwserver-linux(_start+0x2a) [0x55626591fe4a]
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:267] Loading plugins from: /root/nwnx/Binaries
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 0 (NWNX_Administration).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 1 (NWNX_Appearance).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 2 (NWNX_Area).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 3 (NWNX_Chat).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 4 (NWNX_CombatModes).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 5 (NWNX_Creature).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 6 (NWNX_Damage).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 7 (NWNX_Data).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 8 (NWNX_Diagnostics).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 9 (NWNX_Dialog).
E [01:36:49] [NWNX_DotNET] [DotNET.cpp:110] Unable to load libnethost.so. .NET plugin will be unavailable.
E [01:36:49] [NWNX_DotNET] [DotNET.cpp:111] If you're not using the .NET plugin, you can disable this message with 'NWNX_DOTNET_SKIP=y'
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 10 (NWNX_DotNET).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 11 (NWNX_ELC).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 12 (NWNX_Effect).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 13 (NWNX_Encounter).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 14 (NWNX_Events).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 15 (NWNX_Feat).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 16 (NWNX_Feedback).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 17 (NWNX_Item).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 18 (NWNX_ItemProperty).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 19 (NWNX_MaxLevel).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:309] Skipping plugin NWNX_Metrics_InfluxDB due to configuration.
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 20 (NWNX_Object).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 21 (NWNX_Optimizations).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 22 (NWNX_Player).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:309] Skipping plugin NWNX_Profiler due to configuration.
I [01:36:49] [NWNX_Race] [Race.cpp:112] NWNX_ELC is loaded, subscribing to its ValidateCharacter broadcast messages.
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 23 (NWNX_Race).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:309] Skipping plugin NWNX_Redis due to configuration.
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 24 (NWNX_Regex).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 25 (NWNX_Rename).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 26 (NWNX_Reveal).
I [01:36:49] [NWNX_SQL] [SQL.cpp:72] Connecting to type MYSQL
W [01:36:49] [NWNX_SQL] [SQL.cpp:113] Database connection lost. Reconnecting..
I [01:36:49] [NWNX_SQL] [MySQL.cpp:35] Connection info:  host=localhost port=3306 username=nwn
N [01:36:49] [NWNX_SQL] [SQL.cpp:120] Reconnect successful.
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 27 (NWNX_SQL).
ASSERTION FAILURE
  Summary: (rv == FUNCHOOK_ERROR_SUCCESS) failed at (/root/nwnx/NWNXLib/Hooking/FunctionHook.cpp:14)
  Backtrace:
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib8Platform5Debug13GetStackTraceB5cxx11Eh+0x49) [0x7f664156d8e9]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib6Assert4FailEPKcS2_iS2_+0x9d) [0x7f66414fbd4d]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib7Hooking12FunctionHookC2Emm+0x7a) [0x7f6641524a0a]
    /root/nwnx/Binaries/NWNX_ServerLogRedirector.so(_ZN7NWNXLib8Services5Hooks17RequestSharedHookILm3633392EiJP25CNWVirtualMachineCommandsiiEEENS1_17RegistrationTokenEPFvbDpT1_E+0x218) [0x7f66382c3bd8]
    /root/nwnx/Binaries/NWNX_ServerLogRedirector.so(_ZN19ServerLogRedirector19ServerLogRedirectorC1EPN7NWNXLib8Services16ProxyServiceListE+0xa9) [0x7f66382be399]
    /root/nwnx/Binaries/NWNX_ServerLogRedirector.so(PluginLoad+0x22) [0x7f66382be4c2]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib8Services7Plugins10LoadPluginERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS0_16ProxyServiceListE+0x1d5) [0x7f6641581a35]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN4Core8NWNXCore19InitialSetupPluginsEv+0x4cc) [0x7f66414d197c]
    /root/nwnx/Binaries/NWNX_Core.so(_ZN4Core8NWNXCore19CreateServerHandlerEP11CAppManager+0x7ac) [0x7f66414d393c]
    ./nwserver-linux(<UNKNOWN>) [0x55626591b817]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6640079bf7]
    ./nwserver-linux(_start+0x2a) [0x55626591fe4a]
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 28 (NWNX_ServerLogRedirector).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 29 (NWNX_SkillRanks).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:309] Skipping plugin NWNX_ThreadWatchdog due to configuration.
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 30 (NWNX_Tileset).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 31 (NWNX_Time).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:309] Skipping plugin NWNX_Tracking due to configuration.
I [01:36:49] [NWNX_Tweaks] [Tweaks.cpp:65] Disabling the quicksave option on the server
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 32 (NWNX_Tweaks).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 33 (NWNX_Util).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 34 (NWNX_Visibility).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 35 (NWNX_Weapon).
I [01:36:49] [NWNX_Core] [NWNXCore.cpp:320] Loaded plugin 36 (NWNX_WebHook).
I [01:36:49] [NWNXLib] [Commands.cpp:27] Registering command 'runscript'
I [01:36:49] [NWNXLib] [Commands.cpp:27] Registering command 'eval'
I [01:36:49] [NWNXLib] [Commands.cpp:27] Registering command 'evalx'
I [01:36:49] [NWNXLib] [Commands.cpp:27] Registering command 'loglevel'
I [01:36:49] [NWNXLib] [Commands.cpp:27] Registering command 'logformat'
I [01:36:49] [NWNXLib] [Commands.cpp:27] Registering command 'resolve'
I [01:36:49] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:75] (Server) Server Starting Up: 10 Second Heartbeat logging has been disabled
Working Directory For Game Install Is: /root/nwn
Working Directory For Your Resources Is: /root/.local/share/Neverwinter Nights
I [01:36:49] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:75] (Server) Attempting to Use Language: en
I [01:36:49] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:75] (Server) nwsync: reconfigured successfully
I [01:36:50] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:75] (Server) Game is using local port: 5121
I [01:36:50] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:75] (Server) Your cryptographic public identity is: qU2C627/T//O8Xr41d6bE++5XQx/MaJ+lIg7K1/EAGE=
Server: Running...

NWSync: You gave a url, but no hash. Fetching http://85.214.207.43/nwsync//latest.
NWSync: We're now advertising ca225b94cd607ad4aaac035617af668915b12805
Server: Loading module "argonautasvtp"I [01:36:50] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:75] (Server) Loading Module: argonautasvtp
.I [01:36:50] [NWNX_Core] [NWNXCore.cpp:384] Setting up Resource Directory: NWNX:/root/.local/share/Neverwinter Nights/nwnx (Priority: 70000000)
. NWNX Signal Handler:
==============================================================
 NWNX 8193.20 (3009fc867a) has crashed. Fatal error: Segmentation fault (11).
 Please file a bug at https://github.com/nwnxee/unified/issues
==============================================================

  Backtrace:
    /root/nwnx/Binaries/NWNX_Core.so(_ZN7NWNXLib8Platform5Debug13GetStackTraceB5cxx11Eh+0x49) [0x7f664156d8e9]
    /root/nwnx/Binaries/NWNX_Core.so(nwnx_signal_handler+0xa6) [0x7f66414cdd36]
    /lib/x86_64-linux-gnu/libc.so.6(<UNKNOWN>) [0x7f6640097040]
    ./nwserver-linux(_ZN7CResGFF15GetFieldByLabelEP10CResStructPc+0x29) [0x556265fe3159]
    ./nwserver-linux(_ZN7CResGFF7GetListEP8CResListP10CResStructPc+0x42) [0x556265fe4212]
    ./nwserver-linux(_ZN8CNWSArea14LoadAreaHeaderEP10CResStruct+0xa4b) [0x556265b6962b]
Please go to https://beamdog.atlassian.net/servicedesk/ and report this crash to the Neverwinter Nights bug reporter.

Please describe the conditions within which you crashed, indicate your current game version, and attach the following files:

- The error report file at /root/.local/share/Neverwinter Nights/nwserver-crash-1608597418.log.

**Comment by plenarius** [comment]
You're using NWN Server **8193.20**

You need NWN Server **8193.20.1** https://nwnx.io/nwnee-dedicated-8193.20.1.zip

**Comment by FronteraOmega** [comment]
Thanks! :D
