### ISSUE TITLE
Feat usages functions do not work with bard song

### ISSUE THREAD

**Issue by DangerDolphin** [nwnxee/unified#1184]
The functions NWNX_Creature_GetFeatTotalUses and  NWNX_Creature_GetFeatRemainingUses do not work with FEAT_BARD_SONGS.

I think there may a hard cap of 5 in there, as I had 13 usages and it showed 5 / 5 for both values.

The base NWN function IncrementRemainingFeatUses works fine for FEAT_BARD_SONGS so that may be a good place to start.

**Comment by Daztek** [comment]
For each Bard level the Bard gets a new Bard Song feat. At level one they get FEAT_BARD_SONGS, which is 1 use, at 2 levels of Bard they get the feat with ID 355 (Bard_Song_02 ) etc.

You can do the following to get a creature's total uses of their highest bard song feat:

```c
NWNX_Creature_GetFeatTotalUses(oCreature, NWNX_Creature_GetHighestLevelOfFeat(oCreature, FEAT_BARD_SONGS));
```

**Comment by DangerDolphin** [comment]
My bad, thank you!
