### ISSUE TITLE
[Tweaks] Hiding Player Names from Player List on Char Selection shows Names of Newly Entered Players

### ISSUE THREAD

**Issue by eveferon** [nwnxee/unified#1185]
The first time player enters the game, the player list on char selection area is empty, but when the player **stays on that list** and someone enters the game - the list gets updated with this newly entered player's character name. So, basically, spies are  entering the char list after restart and tracking all characters entering the game. If you make a new connection, the list is empty again and only gets updated if you again stay on it.

![player list](https://user-images.githubusercontent.com/4124903/103218948-b173cb80-491c-11eb-9bea-de2bfe18ba70.png)

To reproduce
1. Enable hiding player names setting in tweaks
2. Enter the player list on character selection area and stay there
3. Enter the game with another account 
4. Check the player list of the first client, you will see the name of a newly entered character displayed

**Comment by plenarius** [comment]
It looks like there'd also need to be a hook on `SendServerToPlayerPlayerList_Add` much like what's done in the Experimental SuppressPlayerLogin tweak. https://github.com/nwnxee/unified/blob/master/Plugins/Experimental/Experimentals/SuppressPlayerLoginInfo.cpp

This hook is already being used by Rename though so I'm not sure the best method to deal with this.
