### ISSUE TITLE
Crash - NWNX Tag 8193.20

### ISSUE THREAD

**Issue by Christian-Vassallo** [nwnxee/unified#1186]
[nwserver-crash-1609038069.log](https://github.com/nwnxee/unified/files/5747789/nwserver-crash-1609038069.log)
[nwserver-crash-1609091859.log](https://github.com/nwnxee/unified/files/5747790/nwserver-crash-1609091859.log)
[nwserver-crash-1609124472.log](https://github.com/nwnxee/unified/files/5747791/nwserver-crash-1609124472.log)
[nwserver-crash-1609162558.log](https://github.com/nwnxee/unified/files/5747792/nwserver-crash-1609162558.log)
[nwserver-crash-1609164343.log](https://github.com/nwnxee/unified/files/5747793/nwserver-crash-1609164343.log)
[nwserver-crash-1609167236.log](https://github.com/nwnxee/unified/files/5747794/nwserver-crash-1609167236.log)

Hello everybody, I am experiencing the following errors.
The NWNX version was at 8193.20 tag. Now I am trying with the head of the master, let you know if it will happen again.

The module is quite big, from 1.69. Also some characters was being ported with beamdog standard procedure.

**Comment by Daztek** [comment]
Are you using the 8193.20.1 dedicated server package? https://nwnx.io/nwnee-dedicated-8193.20.1.zip

**Comment by Christian-Vassallo** [comment]
Yed I did

$ sha1sum nwserver-linux 
73d4e3b216cb8c5dd810b06c4d8ac492c826b094  nwserver-linux

**Comment by Daztek** [comment]
Can you post your nwnx.txt?

**Comment by Christian-Vassallo** [comment]
of course. All the session or only the last lines?

**Comment by Christian-Vassallo** [comment]
[nwnx-1609164343.txt](https://github.com/nwnxee/unified/files/5748389/nwnx-1609164343.txt)

This is the nwnx realted to nwserver-crash-1609164343.log

They are all similar. In case you need the others, let me know. I am only missing the last nwnx.

**Comment by Daztek** [comment]
From server startup until the crash

**Comment by Christian-Vassallo** [comment]
[nwnx-1609164343.txt](https://github.com/nwnxee/unified/files/5748390/nwnx-1609164343.txt)

Here

**Comment by Christian-Vassallo** [comment]
[Uploading nwnx-1609164343-wholesession.txt…]()

**Comment by Christian-Vassallo** [comment]
[nwnx-1609164343-wholesession.txt](https://github.com/nwnxee/unified/files/5748397/nwnx-1609164343-wholesession.txt)

Here the whole session.

**Comment by Christian-Vassallo** [comment]
Consider that the server is almost empty in terms of players. The only thing players are doing is a simulation of migration from 1.69 to EE by using beamdog method

**Comment by Christian-Vassallo** [comment]
I updated all the nwnx files (included the nss) and I am running in gdb mode. Let you know about next crash.

**Comment by Christian-Vassallo** [comment]
Hello guys, I have been able to get a server crash with the last version of 8193.20 by analyzing with GDB.

Here what happened.

D [15:33:51] [NWNX_Core] [Events.hpp:128] Returning value '1'. Event 'PrepareQuery', Plugin: 'NWNX_SQL'.
D [15:33:51] [NWNXLib] [Events.cpp:41] Calling event handler. Event 'ExecutePreparedQuery', Plugin: 'NWNX_SQL'.
I [15:33:51] [NWNX_SQL] [SQL.cpp:228] Successful SQL query. Query ID: '1232', Query: 'UPDATE `A_PCTiming` SET `LastEvent`=NOW() WHERE `NomePG`='Sergej'', Rows affected: '1'.
D [15:33:51] [NWNX_Core] [Events.hpp:128] Returning value '1232'. Event 'ExecutePreparedQuery', Plugin: 'NWNX_SQL'.
D [15:33:51] [NWNXLib] [Events.cpp:41] Calling event handler. Event 'DestroyPreparedQuery', Plugin: 'NWNX_SQL'.
free(): invalid next size (fast)

Thread 1 "nwserver-linux" received signal SIGABRT, Aborted.
0x00007ffff786518b in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff786518b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7844859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff78af3ee in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff78b747c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff78b8d2c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x000055555568202f in ?? ()
#6  0x0000555555d42aa5 in ?? ()
#7  0x0000555555d46643 in ?? ()
#8  0x00005555558f8d92 in ?? ()
#9  0x0000555555d2504d in ?? ()
#10 0x0000555555d267d9 in ?? ()
#11 0x0000555555d2764a in ?? ()
#12 0x00005555557ae184 in ?? ()
#13 0x000055555584d515 in ?? ()
#14 0x000055555585ffca in ?? ()
#15 0x00007ffff7e75a0a in NWNXLib::Hooking::FunctionHook::CallOriginal<int, CServerExoAppInternal*> (this=0x55555bed3680)
    at /opt/nwn-ee/nwnx/unified/NWNXLib/./Hooking/FunctionHook.hpp:21
#16 NWNXLib::Services::HooksImpl::HookLandingHolderShared::HookLanding<3194400ul, int, CServerExoAppInternal*> (arg1=0x55555bfe32f0)
    at /opt/nwn-ee/nwnx/unified/NWNXLib/./Services/Hooks/HooksImpl.hpp:114
#17 0x000055555562f79d in ?? ()
#18 0x00007ffff78460b3 in __libc_start_main ()
--Type <RET> for more, q to quit, c to continue without paging--
  o.6
#19 0x0000555555632e8a in _start ()

**Comment by Christian-Vassallo** [comment]
Solved upgrading nwnx.
