### ISSUE TITLE
Deprecate Time Plugin in favour of sqlite functions

### ISSUE THREAD

**Issue by plenarius** [nwnxee/unified#1218]
Can be easily managed with sqlite now. See https://sqlite.org/lang_datefunc.html

* Send deprecation warning on Time plugin loaded
* Change nwnx_time to include helper stub inc_sqlite_time and call the functions that exist in that new library
* Default return value of GetSystemDate to `%m/%d/%Y` but provide an optional format string argument
* Default return value of GetSystemTime to `%H:%M:%S` but provide an optional format string argument
* include new GetSystemDateTime for both that defaults to `'%Y-%m-%d %H:%M:%S'` but provide an optional format string argument
* GetHighResTimeStamp will now only report in milliseconds instead of microseconds as that's all sqlite provides, should be okay

**Comment by Daztek** [comment]
You can't take away my microseconds, orth, you will regret this!

**Comment by milliorn** [comment]
I use time and don't use sqlite at all.

**Comment by plenarius** [comment]
> I use time and don't use sqlite at all. I really hope I don't have to do sql for the sake of time.

sqlite is built into nwn now, I'm not sure I understand your concern nor do I understand why you think you have to "do sql", with this change you'll not have to do any sql as much as you don't have to do any c++ currently

Old way:

```c
#include "nwnx_time"
int iNow = NWNX_Time_GetTimeStamp();
```

Deprecation period way:

```c
#include "nwnx_time"
int iNow = NWNX_Time_GetTimeStamp();
```

After deprecation

```c
#include "inc_sqlite_time"
int iNow = SQLite_GetTimeStamp();
```

I'm merely requesting we change it to not use c++ any more and instead use the built in sqlite.

The change would simply be:

Old way
```c
int NWNX_Time_GetTimeStamp()
{
    string sFunc = "GetTimeStamp";

    NWNX_CallFunction(NWNX_Time, sFunc);
    return NWNX_GetReturnValueInt(NWNX_Time, sFunc);
}
```

New way
**inc_sqlite_time.nss**
```c
int SQLite_GetTimeStamp()
{
    string stmt = "SELECT strftime('%s','now');";
    sqlquery sqlQuery = SqlPrepareQueryObject(GetModule(), stmt);
    return SqlGetInt(sqlQuery, 0);
}

**Comment by zunath** [comment]
The Time plugin was a specific request from the Annakolia server a few years ago. They had a particular format they needed for their code conversion from 1.69 into EE. Not opposed to deprecating it - I don't personally use it - but that's one server I know will be impacted by the deprecation and eventual removal of the plugin.

**Comment by mtijanic** [comment]
For the microseconds, we should keep it (in util) as that's a nice and easy way to do ghetto profilers. Millisecond precision is not always sufficient.

Everything else will be faster and simpler with the wrappers proposed.
