### ISSUE TITLE
Request:  implement GetPCFileName

### ISSUE THREAD

**Issue by ELadner** [nwnxee/unified#122]
(previously in nwnx_funcs)

```
/* Get oPC's bic file name */
string GetPCFileName (object oPC);
```

**Comment by mtijanic** [comment]
What would be the use case for this? We already provide a delete character function, and I really don't want to provide generic file operations access..

**Comment by ELadner** [comment]
Er..  Legacy code?  I'll look at rewriting the function to use the new Admin functions.

**Comment by burmashave** [comment]
> For the record, I'm not opposed to this function, I'm opposed to DeleteFile() - and if that was the only use then it's not worth the effort. If you still have a use for it outside of deletion, reopen this.

I'm looking for a way for a persistent world to uniquely identify a character without having to use a character's name. A .bic file would be unique for a CD key, so it seems like it might work for that purpose, no? That's why I was hoping to find something like GetPCFileName().

**Comment by Daztek** [comment]
NWNX_Player has the following function:

> // Get the name of the .bic file associated with the player's character.
string NWNX_Player_GetBicFileName(object player);

Would that do what you want?

**Comment by burmashave** [comment]
> Would that do what you want?

Good grief, how did I miss that? Yes, that would work perfectly. Thanks!
