### ISSUE TITLE
Feature Request: Flurry of Blows & NWNX_Weapon_SetWeaponIsMonkWeapon

### ISSUE THREAD

**Issue by Mizzajl** [nwnxee/unified#125]
This function currently does not allow the weapon to use Flurry of Blows, any plan to incorporate it into the function or make a separate function to allow a weapon to to be used with Flurry of Blows?

**Comment by Mizzajl** [comment]
Thanks, those nwnx2 functions look nice :)
would it be possible perhaps to make it possible to set these settings to a specific item or for a specific creature wielding the item? without it affecting everyone else?

**Comment by mtijanic** [comment]
Done, I believe in #236 , can be closed.
