### ISSUE TITLE
Race

### ISSUE THREAD

**Issue by Energia00** [nwnxee/unified#1256]
I am trying to activate the Aasiman race by following the example on the site. I modified the racialtype.2da file by adding the RacialModsTable column. I created the racemod_aasimar.2da file and put them in the server override folder.

Does not work.

For testing I tried these operations with the scripts available
NWNX_Util_Get2DARowCount ("racialtype") confirms the presence of the file and indicates the correct lines (includes line 30 of the Asimar)
NWNX_Util_Get2DARowCount ("racemod_aasimar") confirms the presence of the file and shows me the correct lines

However Aasimar does not appear.

So I tried this function NWNX_Race_LoadRacialModifiers ("Label"); and I realized that it is reading some other file because don't find line 30. To confirm, I changed some values in racialtype.2da file (deleted lines, changed values) but I always read the official values of a standard and unmodified file.

Can you tell me where I'm wrong?
Thank you

I attach 2da files with extension changed to txt for upload

[racemod_aasimar.2da.txt](https://github.com/nwnxee/unified/files/5964912/racemod_aasimar.2da.txt)
[racialtype.2da.txt](https://github.com/nwnxee/unified/files/5964913/racialtype.2da.txt)

**Comment by TotallyNotLoinne** [comment]
Did you also put the .2da files on the client folder? You need those both on client and the server to work.

After that, you need `NWNX_Race_LoadRacialModifiers();` , the "Label" will make it read wrong column.

**Comment by Energia00** [comment]
NWNX_Util_Get2DARowCount ("racialtype") replies with the exact number of rows 31 (with the Aasimar row added)
If I delete it from the override folder, the number that appears is 30

NWNX_Util_PluginExists ("NWNX_Race") answers 1

The 2da files are also in the client override folder

I put some debug lines in the "NWNX_Race_LoadRacialModifiers" function and noticed that it stops reading line 30 (so it reads up to the Ooze race) and does not find the RacialModsTable column.

The Get2DAString function don't find the RacialModsTable column

I beleve that NWNX_Util_Get2DARowCount reads the right file (if I change the file, a different number answers) but NWNX_Race_LoadRacialModifiers reads another file and not the one in the "override" folder (Whichever value I change, the answer is always with the data from the "official" file).

**Comment by Daztek** [comment]
In racialtypes.2da, try adding `****` in the `RacialModsTable` column for all other races.

**Comment by Daztek** [comment]
Also, you're using `racialtype` as 2da name, while it should be `racialtypes`

**Comment by Energia00** [comment]
My god! racialtypes!!! :-) Thank you!!!!!!

last problem:
in the columns Name, ConverName, ConverNameLower, NamePlural I put 100 (a random number). 
Where do I find the list of the right numbers to make Aasimar appear? (100 is "next server" :-) )

**Comment by Energia00** [comment]
I found this page http://www.bastionsofwar.com/temp/dialog.166.tlk.txt

Aasimar is 8291

**Comment by Energia00** [comment]
can i ask for more help, please?

I am following these instructions https://docs.google.com/document/d/1eYRTd6vzk7OrLpr2zlwnUk7mgUsyiZzLoR6k54njBVI/edit#

I downloaded and ran this command
./nwsync_write --description = "Ladiun" ~ / nwn / nwsync ~ / nwn / userdir / modules / Ladiunrazze.mod

my server doesn't have hak or tlk and so it wrote that it didn't find anything to extract. I only have 2da files in the override folder. How to tell him he has to look for overrides and not hak / tlk?

nwsync_write created two (now empty) folders date and manifest. 
Will I have to copy these two folders (and the content) or just the 2da on the web site?


Is this the command to start the game? It gives error
cd $ {NWN_DIR}
$ {NWN_DIR} / nwserver-linux \
-module "ladiunrazze" \
-nwsyncurl http://ladiun.it/nwsync
