### ISSUE TITLE
[RFE] NWNX_Object - Get/SetName and Get/SetDescription by language

### ISSUE THREAD

**Issue by silent-rock** [nwnxee/unified#1257]
Base GetName and GetDescription functions return english translations (for object like items, creatures, areas etc), no matter what language we have set up serverside.

It would be great to be able to workaround this bug by getting/settings names and descriptions with certain lang:
`NWX_Object_GetName(object oObject, int bOriginalName, int nLanguage);`
`NWX_Object_SetName(object oObject, string sNewName, int nLanguage);`
`NWX_Object_GetDescription(object oObject, int bOriginalDescription, int bIdentifiedDescription, int nLanguage);`
`NWX_Object_SetDescription(object oObject, string sNewName, int bIdentified, int nLanguage);`

**Comment by Arvirago** [comment]
Yes! And I was blaming some coworkers who have the toolset in English...

**Comment by silent-rock** [comment]
https://github.com/nwnxee/unified/pull/1276 made this request obsolete.
