### ISSUE TITLE
Segfault from missing Metrics plugin environment variables

### ISSUE THREAD

**Issue by Mictali** [nwnxee/unified#1261]
When trying to run the latest server build the engine was crashing on startup with a segfault listed in GetAddrInfo.  It turns out the failure was being caused because the Metrics plugin was not finding the environment variable NWNX_METRICS_INFLUXDB_HOST and was passing a null to the getaddrinfo function.

The error is caught in the NWNXCore component inside a try/catch block and it doesn't provide any details on where the actual error occurred.

Suggest that if NWN_Metrics_InfluxDB is going to require these variables that it should generate an additional error message if they are missing.

**Comment by Daztek** [comment]
Should be fixed in #1457
