### ISSUE TITLE
Help: NWNX_ON_VALIDATE_USE_ITEM

### ISSUE THREAD

**Issue by Energia00** [nwnxee/unified#1277]
I created this code but I have problems. If I only use the NWNX_ON_VALIDATE_ITEM_EQUIP_AFTER event I can not make certain items wear but if I use it together with NWNX_ON_VALIDATE_USE_ITEM_AFTER I can have two problems. Either the game freezes while I log in, or the character is naked and the inventory seems empty (objects are in the inventory but they are invisible and not selectable)

Can you help me? Thank you

In OnLoadMod
#include "nwnx_events"
void main()
{
    NWNX_Events_SubscribeEvent("NWNX_ON_VALIDATE_ITEM_EQUIP_AFTER", "event_itemequipa");
    NWNX_Events_SubscribeEvent("NWNX_ON_VALIDATE_USE_ITEM_AFTER", "event_itemafter");
.....

in event_itemafter
#include "nwnx_events"
#include "eventi"

void main()
{
    object oPC = OBJECT_SELF;
    object oItem = StringToObject(NWNX_Events_GetEventData("ITEM_OBJECT_ID"));
    int isGod = IsDemiGod(oPC);
    int aType = GetAlignmentGoodEvil(oPC);
    int sAlign = AllineamentoOGGETTO(oItem);

    if (GetTag(oItem) == "jn_god")
    {
       if (((aType == ALIGNMENT_GOOD && sAlign == CONST_ALIGN_GOOD) ||
          (aType == ALIGNMENT_NEUTRAL && sAlign == CONST_ALIGN_NEUTRAL) ||
          (aType == ALIGNMENT_EVIL && sAlign == CONST_ALIGN_EVIL))
           && isGod == 1)
            {NWNX_Events_SetEventResult("1");} // OK
        else
            {NWNX_Events_SetEventResult("0");} // NO
    }
    else
    {
        NWNX_Events_SetEventResult("1");
    }
}

**Comment by mtijanic** [comment]
Hello, and apologies for a really late response. I hope you have resolved your issue by now.

I'm afraid we can't really provide scripting help in the issues section (it would drown down actual bugs and feature requests). You will find our [discord server](https://discord.gg/hxTt8Fr) has dozens of people in all timezones that are willing to provide real time assistance with scripting, so please ask there.
