### ISSUE TITLE
[NWNX_Administration] Crash during Shutting down

### ISSUE THREAD

**Issue by Christian-Vassallo** [nwnxee/unified#1279]
Hello guys,
Let me report the following problem.

My server is killed everyday at 4AM by using the function

`D [04:01:10] [NWNXLib] [Events.cpp:49] Calling event handler. Event 'ShutdownServer', Plugin: 'NWNX_Administration'.
`
and it is rebooted by a bash script after 1 minute of waiting.
The reboot works quite well, however - sometimes - the server fails to shut down and the whole system does not reboot.

Here the snaptshot of the end. 

```
D [04:01:11] [NWNXLib] [Events.cpp:49] Calling event handler. Event 'ShutdownServer', Plugin: 'NWNX_Administration'.
N [04:01:11] [NWNX_Administration] [Administration.cpp:96] Shutting down the server!
Server: Exiting...
I [04:01:11] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:80] (Server) Server Shutting Down
double free or corruption (out)
 NWNX Signal Handler:
==============================================================
 NWNX 8193.20 (61384467b6) has crashed. Fatal error: Program aborted (6).
 Please file a bug at https://github.com/nwnxee/unified/issues
==============================================================
```

From NWNX report crash we have:
/opt/nwn-ee/nwnx/unified/Binaries/NWNX_Core.so(nwnx_signal_handler+0xdc)[0x7f7b0b5d971c]
/opt/nwn-ee/nwnx/unified/Binaries/NWNX_Core.so(_ZN4Core8NWNXCore20DestroyServerHandlerEP11CAppManager+0x203)[0x7f7b0b5dbbe3]

I attached the crash log and the nwnx.txt (forgive me, I just remove the useless info, leaving the first 30min and the last 30mins of 24h).
```
[nwnx.txt](https://github.com/nwnxee/unified/files/6101212/nwnx.txt)
[nwserver-crash-1615086071.log](https://github.com/nwnxee/unified/files/6101213/nwserver-crash-1615086071.log)

```
Some info for you:
I was in master, commit: d5bb8271
which should be almost the last one.
[nwnx.txt](https://github.com/nwnxee/unified/files/6101246/nwnx.txt)
[nwserver-crash-1615086071.log](https://github.com/nwnxee/unified/files/6101247/nwserver-crash-1615086071.log)

**Comment by mtijanic** [comment]
Can you try setting `NWNX_CORE_HARD_EXIT=y` in your startup script?

**Comment by Christian-Vassallo** [comment]
I took a while before answering. It works. Thank you

**Comment by Christian-Vassallo** [comment]
Hi guys,

I tried your suggestion to add NWNX_CORE_HARD_EXIT but nothing changed.

At 4AM, sometime it happens this (correct):

`D [04:01:09] [NWNXLib] [Events.cpp:49] Calling event handler. Event 'ReadDataInActiveRow', Plugin: 'NWNX_SQL'.
D [04:01:09] [NWNX_Core] [Events.hpp:46] Returning value '04:01:09'
D [04:01:11] [NWNXLib] [Events.cpp:26] Plugin 'NWNX_Administration', event 'ShutdownServer' not found, trying dlsym()
D [04:01:11] [NWNXLib] [Events.cpp:49] Calling event handler. Event 'ShutdownServer', Plugin: 'NWNX_Administration'.
N [04:01:11] [NWNX_Administration] [Administration.cpp:96] Shutting down the server!
I [04:01:11] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:80] (Server) Server Shutting Down
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Weapon
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Visibility
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Util
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Tweaks
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Time
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Tileset
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_SkillRanks
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_ServerLogRedirector
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_SQL
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Reveal
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Rename
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Race
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Player
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Optimizations
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Object
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_ItemProperty
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Item
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Feedback
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Feat
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Events
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Encounter
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Effect
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_ELC
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Dialog
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Diagnostics
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Damage
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Creature
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_CombatModes
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Chat
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Area
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Appearance
I [04:01:13] [NWNXLib] [Plugin.cpp:81] Unloading plugin NWNX_Administration`


sometimes not:
```
 [04:01:06] [NWNX_Core] [Events.hpp:46] Returning value '1'
D [04:01:06] [NWNXLib] [Events.cpp:49] Calling event handler. Event 'ReadNextRow', Plugin: 'NWNX_SQL'.
D [04:01:06] [NWNX_Core] [Events.hpp:23] Pushing argument '0'
D [04:01:06] [NWNXLib] [Events.cpp:49] Calling event handler. Event 'ReadDataInActiveRow', Plugin: 'NWNX_SQL'.
D [04:01:06] [NWNX_Core] [Events.hpp:46] Returning value '04:01:06'
D [04:01:08] [NWNXLib] [Events.cpp:26] Plugin 'NWNX_Administration', event 'ShutdownServer' not found, trying dlsym()
D [04:01:08] [NWNXLib] [Events.cpp:49] Calling event handler. Event 'ShutdownServer', Plugin: 'NWNX_Administration'.
N [04:01:08] [NWNX_Administration] [Administration.cpp:96] Shutting down the server!
**I [04:01:08] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:80] (Server) Server Shutting Down**
--- MANUAL RESTART ---
N [08:01:35] [NWNX_Core] [NWNXCore.cpp:521] Loading NWNX.
I [08:01:35] [NWNX_Core] [NWNXCore.cpp:241] Loading plugins from: /opt/nwn-ee/nwnx/unified/Binaries
D [08:01:35] [NWNXLib] [Plugin.cpp:34] Loading plugin 'NWNX_Administration'
```

I can just upload you the backtrace, the nwnx.txt is always the same.

[nwserver-crash-1618970471.log](https://github.com/nwnxee/unified/files/6372512/nwserver-crash-1618970471.log)

**Comment by stenly87** [comment]
Hi.
I have the same problem. Same log. Crash is random. Only on shutdown. 
Enabled plugin list:
export NWNX_SQL_SKIP=no
export NWNX_OPTIMIZATIONS_SKIP=no
export NWNX_TWEAKS_SKIP=no
export NWNX_WEBHOOK_SKIP=no
export NWNX_RENAME_SKIP=no
export NWNX_ELC_SKIP=no
export NWNX_CHAT_SKIP=no
export NWNX_ADMINISTRATION_SKIP=no
export NWNX_EVENTS_SKIP=no
export NWNX_OBJECT_SKIP=no
export NWNX_AREA_SKIP=no
export NWNX_CREATURE_SKIP=no
export NWNX_DATA_SKIP=no
export NWNX_DAMAGE_SKIP=no
export NWNX_ITEM_SKIP=no
export NWNX_ITEMPROPERTY_SKIP=no
export NWNX_PLAYER_SKIP=no
export NWNX_UTIL_SKIP=no
export NWNX_RACE_SKIP=no
export NWNX_DIALOG_SKIP=no
export NWNX_FEAT_SKIP=no
export NWNX_FEEDBACK_SKIP=no
export NWNX_SERVERLOGREDIRECTOR_SKIP=no
export NWNX_SKILLRANKS_SKIP=no
export NWNX_VISIBILITY_SKIP=no
export NWNX_WEAPON_SKIP=no
export NWNX_EFFECT_SKIP=no

Could the error be related to threads?

**Comment by mtijanic** [comment]
> I can just upload you the backtrace, the nwnx.txt is always the same.

Please post the stdout/stderr output and not nwnx.txt

**Comment by Christian-Vassallo** [comment]
the problem was related to https://github.com/nwnxee/unified/issues/1487

it is fixed nowz

**Comment by Daztek** [comment]
Alrighty, closing
