### ISSUE TITLE
[BUG] NWNX_Creature_DoItemCastSpell

### ISSUE THREAD

**Issue by ud4ever** [nwnxee/unified#1379]
NWNX_Creature_DoItemCastSpell does not work if caster/target position below ground level, nwnx log shows following:

E [2021-07-01 19:44:40] [NWNXLib] [Events.cpp:56] Plugin 'NWNX_Creature' failed event 'DoItemCastSpell'. Error: ASSERTION FAILURE: (z >= 0.0f) in NWScript: dlg_citycaster
W [2021-07-01 19:44:40] [NWNXLib] [Events.cpp:62] Argument stack not empty after running NWNX_Creature::DoItemCastSpell from dlg_citycaster.ncs. Discarding unused arguments

**Comment by Daztek** [comment]
Technically not really a bug just an assert that can probably go, I'll remove it in a bit
