### ISSUE TITLE
[NWNX_Effect] Stack underflow when calling PackEffect

### ISSUE THREAD

**Issue by Mithreas** [nwnxee/unified#1422]
Tested on build8193.29 and build8193.32 with the same outcome.

The following code fails with a stack underflow error reported in the combat log.

effect SomeFunction(effect eEffect)
{
  struct NWNX_EffectUnpacked eUnpacked = NWNX_Effect_UnpackEffect(eEffect);   
  return NWNX_Effect_PackEffect(eUnpacked); 
}

If I comment out PackEffect and return eEffect instead, there is no error.  I can query values on eUnpacked correctly (e.g. I can retrieve its type) so the unpack appears to work fine.

I turned debug logging on and get the following logs from this function.
[NWNX_Core] [Events.hpp:23] Pushing argument 'EffectID:53978
[NWNXLib] [Events.cpp:49] Calling event handler. Event 'UnpackEffect', Plugin: 'NWNX_Effect'.
[NWNX_Core] [Events.hpp:46] Returning value XXX
...for all 41 parameters in the Effect
[NWNX_Core] [Events.hpp:23] Pushing argument XXX
...for all 38 parameters in nwnx_effect/Effect.cpp

And then nothing - not even the log from Events.cpp saying that PackEffect is being called.  So the error is occurring very early in the engine, before we actually invoke the PackEffect function.

Likely unrelated, but I also sometimes seem to get the following messages when calling UnpackEffect.  Including for completeness - PackEffect always fails, regardless of whether UnpackEffect generates these messages.  The extra messages occur between "calling event handler" and "returning XXX". 
[NWNXLib] [Events.cpp:62] Argument stack not empty after running NWNX_Effect::UnpackEffect from m_equip.ncs. Discarding unused arguments
[NWNXLib] [Events.cpp:65] Discarding argument XXX
...for all 38 arguments in reverse order

**Comment by Daztek** [comment]
It's not a NWNX or NWN issue, the issue is NWNSC, it can't handle structs in structs. You can either compile your script with the toolset or use an edited nwnx_effect.nss that doesn't have structs in its struct: https://gist.github.com/Daztek/2b998b03ec289330b32ee17fd79fcd7d

**Comment by Mithreas** [comment]
Thank you!  I would never have figured that out myself - works like a charm.
