### ISSUE TITLE
NWNX_TWEAKS_LANGUAGE_OVERRIDE does not work anymore

### ISSUE THREAD

**Issue by silent-rock** [nwnxee/unified#1438]
Loads correctly, but has no effect. Seems to be not working.

`[NWNX_Tweaks] [LanguageOverride.cpp:24] Language override set to 5`

Not sure which update could break it. @BhaalM could you take a look at it?

**Comment by BhaalM** [comment]
Seems to work fine for me. I created an object with two descriptions, one in Spanish and one in English. Changing the configured language gives the expected result. 🤔

I'm currently running version 8193.32

**Comment by silent-rock** [comment]
> 
> 
> Seems to work fine for me. I created an object with two descriptions, one in Spanish and one in English. Changing the configured language gives the expected result. 🤔
> 
> I'm currently running version 8193.32

Testing it on 8193.33, freshest nwnx version.

GetName for area returns english translation, instead of polish (which I've set as lang override - 5).

**Comment by Daztek** [comment]
Areas don't use the tweak, it uses the module language, which apparently hardcoded to english
