### ISSUE TITLE
[FEATURE REQUEST] Add NWNX_ON_EXPERIENCE_GAINED events

### ISSUE THREAD

**Issue by silent-rock** [nwnxee/unified#1450]
Can we have NWNX_ON_EXPERIENCE_GAINED before and after added to nwnx_events plugin?

It would be great to have it skippable aswell.

**Comment by gm-xanther** [comment]
Seconded, this would be really helpful for things like anti-cheat measures, exp boosting items/events, or making creatures that can't give exp like commoners or minion summons.
