### ISSUE TITLE
NWNX_TWEAKS_FIX_MULTICLASS_XP_PENALTY_BUG error

### ISSUE THREAD

**Issue by ZarkIsBad** [nwnxee/unified#1482]
It seems that the multiclass XP penalty bug fix is creating its own issues and hasn't completely fixed others. On a human 13sorcerer/10blackguard/5monk character I was experiencing an XP penalty bug. Normally that isn't an issue without the fix. On another human that is 18 Weapon Master/12 Cleric/4 Monk I am still experiencing an XP penalty, which is what I assume the fix set out to stop as its taking Weapon Master as my favoured class instead of a base class like cleric. I also tried on some other characters who were fighter/weapon master and one monk/shadowdancer/fighter and neither of those had xp penalty so it seems to be working as intended in some cases.

**Comment by Daztek** [comment]
I'm just a dummy, will be fixed shortly
