### ISSUE TITLE
Request - Manage Encounter

### ISSUE THREAD

**Issue by Christian-Vassallo** [nwnxee/unified#152]
Hello everybody and thanks for your work.

One of the big problem in NWN is that encounter are, for most of the time, fixed.
This means that an encounter can be defined only from toolset and it can't be changed through scripts.

The functions with which I can manage the encounter objects are only these:
https://nwnlexicon.com/index.php?title=Category:Encounter_Functions

Example: if I want to have a random group of monster (Bugbear instead of Undead or so on) I can do it with some bypass system but it is a dirty way.

Can you think to add some functions that allow too modify the entries object in the encounter?

Example: 
AddCreaturesInListEncounter(int IndexCreature, string TagCreature, int GSCreature, string ResRefCreature, int isUnique)
SetFactionEncounter(int Function, object Encounter)
etc...

What do you think?

**Comment by mtijanic** [comment]
Done by Daz in #272.
