### ISSUE TITLE
Events: Skip executing event

### ISSUE THREAD

**Issue by Liareth** [nwnxee/unified#16]
We need to allow the Events plugin to skip events.

1. Switch all shared hooks to exclusive hooks.
2. Come up with the API. `void NWNX_Events_SkipEvent()` maybe. Possibly add a comment explaining event skipping is only valid on NWNX events and not user defined events, or do extra work to check if an event has been skipped between invoking each subscribing script.
3. If the API is called, set a flag.
4. Clear the flag on event completion. Figure out a clean way to do this, maybe Events::StartEvent() and Events::FinishEvent() between Events::SignalEvent().
5. If the flag is set, skip calling the original function.

**Comment by Liareth** [comment]
@zunath @mtijanic This is the sort of interface I was thinking of:

https://github.com/Liareth/unified/commit/ff715cc2acd889f21aaf86f6426393d6f98ef66e

**Comment by zunath** [comment]
@Liareth I like it - very similar to 1.69's BypassEvent so I'm on board with it.

What happens if you call SkipEvent in an "After" subscriber? Anything?

**Comment by mtijanic** [comment]
Maybe also a `GetEventSkipped()` to call from the AFTER handler?

**Comment by mtijanic** [comment]
The API is there and most of the vents were migrated by daz. Closing this.
