### ISSUE TITLE
[Feature Request] Trap Events: Location and Object Retrieval

### ISSUE THREAD

**Issue by vicky-dot-bat** [nwnxee/unified#1601]
Discord message link: https://discord.com/channels/382306806866771978/387223972808359936/1085873444018737243

From nwnx_events:
![image](https://user-images.githubusercontent.com/38017628/225592850-60a0f84d-49b0-480b-b6a5-155691bd06c9.png)

There is currently no retrieval for Location floats or Object variables. This would be highly sought-after for people who are trying to reference the object that the trap is being placed on, or the location, correspondingly.

Per Daz, there's already parameters in the system that merely need to be exposed:

> the target object would be pNode->m_pParameter[1]
and the location floats are 2-4

Would greatly appreciate if anyone felt like taking this on.

**Comment by Cjreek** [comment]
Working on it
