### ISSUE TITLE
CNWSItemPropertyHandler missing in .35 API

### ISSUE THREAD

**Issue by Shad000w** [nwnxee/unified#1622]
And thus it is not possible to hook functions like CNWSItemPropertyHandler__RemoveBonusSpellOfLevel.

I was able to workaround the issue by creating a "stub" include file for CNWSItemPropertyHandler and putting the function I needed to hook inside it - surprisingly it worked without issues. But you will probably want to fix this in your API.

**Comment by plenarius** [comment]
This was added in #1693
