### ISSUE TITLE
GUID/UUID plugin

### ISSUE THREAD

**Issue by Urothis** [nwnxee/unified#166]
Could we maybe get a small plugin to generate GUID/UUID, it would be insanely helpful. 

It would remove the current way of generating a random string via nwscript, and then having to confirm that random string isn't being used elsewhere for a unique id.

I found this https://github.com/graeme-hill/crossguid 
It might work for this situation but I'm not sure on dependencies. But cross platform seemed good.

**Comment by mtijanic** [comment]
For the sake of completeness and cleanup, you can just do this on mysql:
```C
string GetUUID() {
     NWNX_SQL_ExecuteQuery("SELECT UUID();");
     NWNX_SQL_ReadNextRow();
     return NWNX_SQL_ReadDataInActiveRow();
}
```

For PgSQL, it's similar, you just need to create an extension first:
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```
And the function name is `uuid_generate_v4()`.

@Urothis think we can close this?

**Comment by ELadner** [comment]
IMO, the time to trip out to the database and back would be an order of magnitude longer than just generating it in native C++.

Also, that requires you to use the SQL plugin where the user may not have been using it before.

With BD talking about implementing SQLite for persistent storage, the SQL plugin may be a thing of the past in six months.

**Comment by Urothis** [comment]
I would have to agree with @ELadner,

While being able to use SQL for the uuid generation is a good placeholder. 

Something attached to the utils plugin and in "native" c++ will probably be much faster than using SQL in the long run.
