### ISSUE TITLE
NWNXLib::API::Constants::SavingThrowType is missing a a value for "Paralysis" (=20)

### ISSUE THREAD

**Issue by Cjreek** [nwnxee/unified#1697]
See title.
Daz promised he'd add this at some point - maybe!

**Comment by mtijanic** [comment]
Was an issue really less work than a PR? 😛 
For such basic stuff you can just go through github web UI

**Comment by Cjreek** [comment]
@mtijanic Daz said I should make an issue https://discord.com/channels/382306806866771978/382914210176172032/1149418267711111188 :P

**Comment by Daztek** [comment]
Only because you're too lazy to make a pr and so you saddle poor daz with more work
