### ISSUE TITLE
'development' folder not working with newest NWNX files?

### ISSUE THREAD

**Issue by ReachPW** [nwnxee/unified#1733]
Typically if you drop a *.ncs script file in the 'development' folder then the server will pick up it next time it's run.

This seems to be not working on latest (BlackBat on discord also is having very similar problem)

I'm testing with latest steam build (88.8193.36-11) on linux.  I tested with these NWNX version:

Doesn't seem to work: 

* latest/NWNX-EE.zip ( build8193.36.11-HEAD )
* build8193.36.11-HEAD/NWNX-EE.zip
* build8193.36.10-HEAD/NWNX-EE.zip

* build8193.36.8-HEAD/NWNX-EE.zip
* build8193.36.7-HEAD/NWNX-EE.zip

Works as previously with this version : 
* build8193.36.7-HEAD/NWNX-EE.zip

Did NOT test with this : 
* build8193.36.9-HEAD/NWNX-EE.zip

Test steps:

1) Was using a simple heartbeat script that prints out message to player `SendMessageToPC(GetFirstPC(), "test 1");`
2) I would change static message in script (ie "test **2**", etc)
3) recompile
4) reupload *.ncs to 'development' folder
5) then watch for new message from game client.

 7-HEAD always picks up newest message on heart beats.  The others didn't seem so untill a hard server restart.

**Comment by ReachPW** [comment]
Sorry, it's late.  Going to close this under user error, lol

Setting this to false "fixes" it: 
`export NWNX_OPTIMIZATIONS_CACHE_SCRIPTS=false;`

**Comment by Daztek** [comment]
I thought I had somehow set it to load by default, but no, it truly is user error :V
