### ISSUE TITLE
Create functionality to mimic realtime plugin

### ISSUE THREAD

**Issue by Urothis** [nwnxee/unified#175]
Functionality this plugin brought, it seems like the old version I found was for windows only. 

Not sure of scope, would just be useful. 

string GetServerLoadTime() -> yyyy-mm-dd hh:mm:ss (when Plugin loads)
string GetServerDate() -> yyyy-mm-dd
string GetServerTime() -> hh:mm:ss
string GetServerDateTime() -> yyyy-mm-dd hh:mm:ss
string GetServerDayName(int iFullname = TRUE) eg Monday or Mon
string GetServerMonthName(int iFullname = TRUE) eg January or Jan
int GetServerYear()
int GetServerMonth()
int GetServerDay()
int GetServerHour()
int GetServerMinute()
int GetServerSecond()
int GetServerUpDays()
int GetServerUpHours()
int GetServerUpMinutes()
int GetServerUpSeconds()
string GetServerUptime() -> hh:mm:ss

**Comment by mtijanic** [comment]
Zunath's NWNX_Time offers all the functionality you need, you just might have to wrap it some more to get the interface you're requesting. Doesn't need any further work in NWNX, though.

https://github.com/nwnxee/unified/blob/master/Plugins/Time/NWScript/nwnx_time.nss

**Comment by Urothis** [comment]
Understood, thank you. 
Closing.
