### ISSUE TITLE
 Port ShowVisualEffectForPC Function from nwnx_visibility

### ISSUE THREAD

**Issue by jennyzahler** [nwnxee/unified#176]
Also saw this one requested on the Beamdog forum: https://forums.beamdog.com/discussion/67501/request-client-specific-visual-effects-something-i-requested-long-ao

I won't go into detail about what makes this plugin so super useful! That's outlined in the post above.

Currently working on a module and encounter massive hurdles trying to port it to EE without this lovely plugin. Hoping for a port!

**Comment by mtijanic** [comment]
bugscrub: This can be closed now, I think

**Comment by mtijanic** [comment]
Belay that. Misunderstood the request, per-player object visibility isn't _quite_ what's requested here.

**Comment by mtijanic** [comment]
Done, can be closed.
