### ISSUE TITLE
Feature request: open object inventory GUI

### ISSUE THREAD

**Issue by weavejester** [nwnxee/unified#183]
Is it possible for a function to open an creature or placeable inventory, bypassing the usual `ActionInteractObject`, preferably without regard to distance?

I'm thinking of a function like:

```
void NWNX_Player_ForceOpenInventoryGUI(object player, object container);
```

I notice there's a function `CNWSPlayerInventoryGUI` that suggests this might be possible, and a function `SendServerToPlayerGuiContainerObject_Status` that maybe could be used? I don't yet have a good enough understanding of the code to figure out if this is possible. If someone could point me in the right direction I could have a bash at this, or else confirm that this isn't currently possible.

My reason for wanting this is to create treasure chests that generate different loot for different players. Each player that opens the chest will get a different inventory with loot that only they can see. This lessens the need to divvy up loot at the end of the dungeon.

I've played around with creating invisible objects by the chest that contain the instanced loot, and then using `ActionInteractObject` to force the player to open them, but I frequently ran into pathing problems, as the PCs needed a clear path to the invisible inventory objects. Being able to force the inventory GUI up on screen would solve the issue.

**Comment by mtijanic** [comment]
Done, can be closed.
