### ISSUE TITLE
Is Redis deprecated? 

### ISSUE THREAD

**Issue by Urothis** [nwnxee/unified#193]
Myself and afew other builders can't seem to get redis working. 

Anytime we try to write to redis. we get a hard crash. 
Was just wondering if we were missing something or if the functionality actually worked.

**Comment by mtijanic** [comment]
I'd go ahead and say yes, since it's @niv 's pet project, and I think he has no desire to maintain it. Can you post a stacktrace of the crash, maybe it's something we could fix?

**Comment by niv** [comment]
Deprecated is a harsh word. ;) It worked back when I first published it. I don't mind fixing whatever is broken, but I'll need a repro then, and some time to get it set up again. Once it's working, maintaining it for new redis versions (with new commands) should be trivial.
