### ISSUE TITLE
SQL: Transparent blocking reconnect on all supported backends

### ISSUE THREAD

**Issue by Liareth** [nwnxee/unified#2]
NWNX_SQL should reconnect transparently (and block the server while doing so in order to not leak unhandled errors) when the connection was lost.

Ideally, some kind of capped exponential falloff.
Also, log messages to indicate the condition.

ref https://support.baldursgate.com/issues/34068

**Comment by Liareth** [comment]
Mostly done by @mtijanic, now just needs @ELadner for PgSQL support.

**Comment by mtijanic** [comment]
I think this can be closed now.
