### ISSUE TITLE
Rate limit for webhooks?

### ISSUE THREAD

**Issue by urothis** [nwnxee/unified#204]
I've hit the discord rate limits using webhooks to discord, and I've been doing some research on how to solve this.

More information on the rate limits of discord here.
https://discordapp.com/developers/docs/topics/rate-limits

Main point being:
"Because we may change rate limits at any time and rate limits can be different per application, rate limits should not be hard coded into your bot/application. In order to properly support our dynamic rate limits, your bot/application should parse for our rate limits in response headers and locally prevent exceeding of the limits as they change."

**Comment by Urothis** [comment]
I wanted to expand this issue, to possibly include a feature request to have the plugin return a 1 or a 0 for if the webhook was successful. That way we can handle our own logic of delivery failure.

**Comment by mtijanic** [comment]
> I wanted to expand this issue, to possibly include a feature request to have the plugin return a 1 or a 0 for if the webhook was successful. That way we can handle our own logic of delivery failure.

This isn't quite possible since the web requests are sent asynchronously from a side thread, and you really don't want to stall the main thread until they're done to check the result from scripts. We could maybe signal an event when the webhook sending fails, so you can try again.

**Comment by plenarius** [comment]
Working on this.
