### ISSUE TITLE
NWNX Names

### ISSUE THREAD

**Issue by Christian-Vassallo** [nwnxee/unified#206]
Hello everybody,

I have just a question.

What about the nwnx names plugin? Is it working? 

I didn’t have the time to test it and I am trying to understand if the plugin is working or if it must be developed because I have seen a TODO somewhere there

Thank you

**Comment by Liareth** [comment]
Unfortunately, Names has not been ported for the latest version of NWN: EE. It takes a lot of effort to update each version as it's a manual process. If anyone wants to develop it, they can use the framework of the existing plugin and rewrite the assembly in the plugin itself as appropriate.

**Comment by jennyzahler** [comment]
At the moment, even a plugin that allows a permanent name change would be helpful. Systems such as Arelith's disguise could then be ported (albeit with more work).

The lack of development on this front is such a huge shame.

**Comment by Christian-Vassallo** [comment]
Hi guys,

If you explain me know how to find the memory address to make the plugin working, I will keep it updated each patch. But I need a little “finger” of help

**Comment by Christian-Vassallo** [comment]
I have seen that  Arelith still has the disguise system. How is it possible?
Are they updating every time their plugin to make it working or something else?

**Comment by mtijanic** [comment]
@Christian-Vassallo with the new Rename plugin, does this cover your required usecase? If so please close this, and we can open another issue if someone actually needs per-player names. It's better for prioritization if the issues filed are more specific.

**Comment by mtijanic** [comment]
I'm going to close this as we have basic renaming functionality now. N:N player name mapping is not implemented. If someone needs it, please open another request.
