### ISSUE TITLE
Where does ServerLogRedirector write the log file?

### ISSUE THREAD

**Issue by Seablack** [nwnxee/unified#214]
Hello everybody,

Excuse my ignorance and my English. I uploaded a PW thanks your NWNX:EE. All good except that I can not get the log file in the logs.0 folder, it's in the same place where I have the  * .so files. I do not understand. 

I have just a question. Where does ServerLogRedirecto write the log file?.  And if there is any way to configure the ServerLogRedirector, where does it has to write the log file?.

Thanks for everything.

**Comment by mtijanic** [comment]
Hi, sorry for the late reply. You can think of ServerLogRedirector as a T junction (like `tee`) that leaves the logs where they were, but also sends a copy to `stdout`. Typically, the script you use to preload NWNX and run nwserver will redirect output to a file, such as:

     LD_PRELOAD=NWNX_Core.so ./nwserver-linux -module 'mymod' > log.txt

in which case `log.txt` will contain logs from both NWN and NWNX.
