### ISSUE TITLE
Issues with Using nwnx_object Functions

### ISSUE THREAD

**Issue by idoseter** [nwnxee/unified#226]
I have issues running he nwnx_object functions. Especially the GetLocalVariableCount and GetLocalVariable variations in NWNXEE. They either return zero or null but nothing else. Ran the nwnx_object_t.nss file to see if I am doing anything wrong, but got failure results there as well:

[Thu Oct 04 07:54:48] NWNX_Object unit test begin..
[Thu Oct 04 07:54:48] NWNX_Object: GetLocalVariableCount() failed
[Thu Oct 04 07:54:48] NWNX_Object: GetLocalVariable() failed
[Thu Oct 04 07:54:48] NWNX_Object: GetLocalVariable() failed
[Thu Oct 04 07:54:48] NWNX_Object: StringToObject() failed
[Thu Oct 04 07:54:48] NWNX_Object: GetEventHandler() is deprecated. Use native GetEventScript() instead
[Thu Oct 04 07:54:48] NWNX_Object: GetEventHandler() success
[Thu Oct 04 07:54:48] NWNX_Object: SetEventHandler() is deprecated. Use native SetEventScript() instead
[Thu Oct 04 07:54:48] NWNX_Object: GetEventHandler() is deprecated. Use native GetEventScript() instead
[Thu Oct 04 07:54:48] NWNX_Object: SetEventHandler() success
[Thu Oct 04 07:54:48] NWNX_Object: SetEventHandler() is deprecated. Use native SetEventScript() instead
[Thu Oct 04 07:54:48] NWNX_Object: SetPosition() failed
[Thu Oct 04 07:54:48] NWNX_Object: SetMaxHitPoints() failed
[Thu Oct 04 07:54:48] NWNX_Object: SetCurrentHitPoints() failed
[Thu Oct 04 07:54:48] NWNX_Object: GetPortrait() failed
[Thu Oct 04 07:54:48] NWNX_Object: SetPortrait() failed
[Thu Oct 04 07:54:48] NWNX_Object: Serialize() failed
[Thu Oct 04 07:54:48] Serialized chicken: 
[Thu Oct 04 07:54:48] NWNX_Object: Deserialize() failed
[Thu Oct 04 07:54:48] Deserialized  in 
[Thu Oct 04 07:54:48] NWNX_Object unit test end.

Any insights on what could be the issue?

**Comment by mtijanic** [comment]
That looks like you did not install/load NWNX properly. Either the core didn't load at all, or the object plugin (`NWNX_Object.so`) was missing.

It would help if you post the server output when starting the module.

**Comment by idoseter** [comment]
I have added the .nss files(Including the NWNX_core and NWNX_Object) directly to my module.
I also placed the .SO files in the same folder where the nwserver.exe file is located.

For now I am just trying to run it locally in the module and testing it as a DM - Not in a dedicated server yet.

I still can't seem to make it work sadly. If you could provide instructions to extract the data you need to figure what went wrong, I would gladly provide it.

**Comment by mtijanic** [comment]
Unfortunately, nwnxee only works on a dedicated linux setup, so that approach won't work. If you don't want to deal with Linux, there's a docker image that you can run on Windows (it's similar to a prebuilt Virtual Machine that has linux, nwn and nwnx preinstalled). 

There is a bit of documentation about it here: https://hub.docker.com/r/nwnxee/unified/ (you can also find plenty of general docker documentation online). If you hit any issues, best ask the docker experts on discord: https://discord.gg/hxTt8Fr
