### ISSUE TITLE
Hook management- order and priority 

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#228]
Is it possible to install multiple hooks to the same method - and if so: are we, the plugin developers able to control the priority / order in which hooks get processed?

Use case: a chat hook exists from plugin 1
But plugin 2 wants to take player input from the player via chat input too.
This input may be sensitive in nature and would not want to have another plugin processing the input.
This would normally be something that the server admin would worry about- I’m just thinking along the lines of plugin development could be aimed at automating the setup of much of these things outside of server admin having to do anything.

**Comment by Liareth** [comment]
Yes, you can have several shared hooks on the same function. No, it is not possible to control the order in which hooks get processed, not pass any information between hooks. (it could be possible if someone implemented it in a sensible way)

The biggest improvement to the hook system right now would allow shared hooks to also hook a location where an exclusive hook has hooked - and the exclusive hook may query the core to dispatch the calls to the shared hook.

In your specific example, it would make more sense to write a system in nwscript which sends that specific input to the place it needs to go. There's no need to have two plugins hook that directly. Alternatively, if you really need a second plugin, you could use the messaging subsystem to broadcast that a chat message has occurred, which the second plugin could subscribe to. Search the code for `m_messaging` to see how this works. I believe there are examples in the Event and Profiler plugins and there may be more elsewhere.
