### ISSUE TITLE
Any list of plugin status against latest EE?

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#229]
I suspect I know the answer is going to be: No

I was just wondering if there is anyway we can get some sort of dashboard that shows the plugins and their status against latest EE  build?

I read an issue previously that said that Names plugin was not currently working for latest EE build.
It would be handy if we had a green, amber, red status for each plugin so we could know if they are working.

Eg: Can this be done via unit tests or something?

I have previously done it in some of my own plugin development, where a module could be wrote that has a series of unit tests programmed in via nwscript - kicked off via the OnModLoad event
Then based on log output, you could derive a pass or fail status.

**Comment by mtijanic** [comment]
I think it's okay to commit that all in-tree plugins will work with the latest version at all times. Stuff like the old names plugin has been removed (we got a new Rename plugin that does the same thing). I'm gonna close this down with a policy "any plugin you see under `Plugins/` is working, and no need for color coding.

Let me know if you disagree with the policy.
