### ISSUE TITLE
Feature Request: Possess NPC

### ISSUE THREAD

**Issue by Christian-Vassallo** [nwnxee/unified#231]
Hello guys,

I have a request for you.
In the 1.69 version of NWNX we had a really interesting feature: Possess and Unposses Creature.

This function allowed to control, like a familiar, a creature.

https://github.com/NWNX/nwnx2-linux/blob/master/plugins/funcsext/nwnx_funcsext.nss

// Change possession of oPC to oCreature
void PossessCreature(object oPC, object oCreature);

// unpossess creature formerly possessed with PossessCreature()
void UnPossessCreature(object oPC, object oCreature);

What do you think about it?

Many thanks

**Comment by mtijanic** [comment]
I believe the way it was done in 1.69 is exceptionally dangerous, as it could overwrite the player's .bic file with that of the NPC. I could add it with a big fat disclaimer, but I'd rather look at how to make it safe.

**Comment by mtijanic** [comment]
That trick gets rid of a lot of issues, but comes with its own couple of caveats:
- When possessing a familiar you are immune to mind spells
- Map exploration from the familiar is sent back to the player
and I'm not sure what happens to your existing familiar. But overall seems like a better choice.

**Comment by Christian-Vassallo** [comment]
In my PW I use PossessCreature to possess and unpossess (the unpossess function doesn't work).

Actually I made a backup of the file .bic when the PC possess the creature. If something goes wrong (Crash during possess) then the bic is restored. You lose PE and what you did but your PC is safe.

Otherwise no problem. Everytime you unpossess, you jump from a temp area to your PC because you could have visual problem.

**Comment by Christian-Vassallo** [comment]
Hello everybody,

I am sorry to bother you. I would like to know if you had in mind to implement this feature or not. I am going to move from 1.69 to EE and I need to know if this feature should I stop to maintain.

Just to know :)

Thank you
