### ISSUE TITLE
Reset Server after ThreadWatchdog detected a LongStall

### ISSUE THREAD

**Issue by milliorn** [nwnxee/unified#234]
https://github.com/nwnxee/unified/blob/master/Plugins/ThreadWatchdog/ThreadWatchdog.cpp

Can we do a NWNX_Administration_ShutdownServer(); once this is detected?  Is there a reason why this is not done?  Is there something else in Metrics that does the restart or something that keeps the server going?  Currently it seems what happens is that the server hangs and you must restart it manually.

**Comment by Liareth** [comment]
The purpose of the ThreadWatchdog is to submit a metric when it indicates a potential stall on the main thread. Be design it isn't responsible for restarting the server, and it can't even be assumed that a 15 second stall is an unrecoverable lock either - it could just be a long IO operation. A configurable option could be added (defaulting to off) which just kills the server when it detects one of these stalls.

**Comment by mtijanic** [comment]
The metrics system isn't the easiest to set up, unfortunately, so I don't fault people for not using it. It'd be nice if either the metrics could be sent to a simple file, or if the Watchdog had a config option that gives it a file to write to when it detects a hang.

Then you can have a separate process wait on that file and kill nwserver if needed.

**Comment by Urothis** [comment]
Killing the server would be the preferred behavior docker wise. 

If we could expose that into an env setting
NWNX_WATCHDOG_SHUTDOWN=

**Comment by milliorn** [comment]
> A configurable option could be added (defaulting to off) which just kills the server when it detects one of these stalls. 

> 

Can we do this so we can address the hang if we don't have metrics setup or not in use?  Be greatly appreciated and keep things automated.

**Comment by mtijanic** [comment]
I think we can close this now.
