### ISSUE TITLE
[Request] Expand Skill-Based Feats

### ISSUE THREAD

**Issue by Aschent89** [nwnxee/unified#254]
Skill Focus, Epic Skill Focus, Legend Lore.

Details: Allow the inclusion of custom skills into skill-based feats. As it is now, the above feats are stuck impacting vanilla skills however the vast majority of servers change/add skills.

**Comment by mtijanic** [comment]
Possibility we discussed: Add a few columns to feats.2da: `skill1_id, skill1_modifier, skill2_id, skill2_modifier, skill3_id, skill3_modifier`, and read those to get the actual modifiers. That way you can modify any of the hardcoded skill bonuses stuff.
