### ISSUE TITLE
Feature request: SetFeatTotalUses

### ISSUE THREAD

**Issue by silent-rock** [nwnxee/unified#268]
Hi there,

In nwnx_patch plugin for NWN:DE there was a function `NWNXPatch_SetFeatTotalUses`.

It allowed to change feat uses without the necessity of adding separate feats in feats.2da just to increment those uses per class level.

Any chance to create something like that in one of the plugins available here?

**Comment by mtijanic** [comment]
Done by Eric in #287 .
