### ISSUE TITLE
Add GetCustomToken() function

### ISSUE THREAD

**Issue by MhlChesnokov** [nwnxee/unified#269]
possible to add to NWNX_Dialog the function "Get Selected Node Test ()" - which returns the value of the selected string in the dialog (i.e. the contents of <CUSTOM00000> in the string) ???
GetSelectedNodeText()
this would be very convenient for use in dialog systems when using " SetCustomToken()" . in 1.69 it was

**Comment by mtijanic** [comment]
Is this not `GetCurrentNodeText()`? I'm not sure if it would return the actual token or `<CUSTOM123>`, but if the latter, then the request should be for `string GetCustomToken(int nTokenNum);` instead.

**Comment by Daztek** [comment]
`GetCurrentNodeText()` returns `<CUSTOM****>`

**Comment by MhlChesnokov** [comment]
possible to make the NWNX_WebHook plugin work not only with Latin encoding, to make it possible to use different encodings in the plugin.??

**Comment by mtijanic** [comment]
(renaming to better reflect what is needed here)

**Comment by mtijanic** [comment]
This should be fully implemented now, closing.
