### ISSUE TITLE
Administration: Delete Bic File

### ISSUE THREAD

**Issue by Alibertos** [nwnxee/unified#29]
Original project: https://github.com/NWNX/nwnx2-linux/tree/master/plugins/system
Primarily this plugin provide to manage files and directories, eg in a multiplayer pw it's used to delete bic file

**Comment by mtijanic** [comment]
bic delete (with backup and restore) can go into Administration plugin. 

For generic file operations, I'm not sure if we want to give the PW admins that much rope _and_ a branch.

**Comment by Alibertos** [comment]
ok, i changed the thread title

**Comment by mtijanic** [comment]
Added with #37
@Alibertos please close if this works for you.

**Comment by Alibertos** [comment]
It works! tnx
