### ISSUE TITLE
Creature: Override BAB

### ISSUE THREAD

**Issue by Alibertos** [nwnxee/unified#30]
Request new function to set the BAB of a creature overriding the current one.
This function was implemented in funcs plugins for windows, here is the original description

// Sets the Base Attack Bonus Override of oObject to iBaB
// If BAB Override is greater than zero GetBaseAttackBonus will return this instead
// The original BAB can be restored by setting the BAB Override to zero
// The range of iBab is 0 to 254
// Unfortunately this is not a permanent setting as the game calculates the BaB every time a player logs in
void NWNXFuncs_SetBaseAttackBonusOverride(object oCreature, int iBaB);

**Comment by mtijanic** [comment]
Done in PR #63

**Comment by Alibertos** [comment]
Thanks so much

**Comment by mtijanic** [comment]
@Liareth or @Alibertos , please close.
