### ISSUE TITLE
DM Events

### ISSUE THREAD

**Issue by zunath** [nwnxee/unified#32]
A few more things I need as part of my server migration:

- DM Give XP
- DM Take XP
- DM Give Level
- DM Take Level
- On pause event

**Comment by mtijanic** [comment]
Okay, these should _not_ be done like this:
https://github.com/nwnxee/unified/blob/master/Plugins/Events/Events/DMActionEvents.cpp

Instead, hook `CNWSMessage::HandlePlayerToServerDungeonMasterMessage()`, do a switch on the message minor code and either implement the full feature from scratch, or peek and the data and passthrough.
This way there's no inline hooks and no issues with updates.

**Comment by mtijanic** [comment]
Done in #76 (just so no one picks it up for duplicate work)

**Comment by zunath** [comment]
This one looks done. Thanks @mtijanic !
