### ISSUE TITLE
Events Plugin - Trap Trigger Event

### ISSUE THREAD

**Issue by torradmin** [nwnxee/unified#34]
The events plugin is missing hooks for:
- ~~Skill Use~~
- ~~Polymorph~~
- ~~Unpolymorph~~
- ~~Action Mode Toggle (only has stealth)~~
- ~~Crit/Dev Crit (dev crit should also be cancellable - see other issue!)~~
- Trap Trigger
- ~~Trap Set~~

**Comment by Mizzajl** [comment]
Hi, just wanted to say that I also would like to be able to detect skill use and replace the default behaviour with a custom script :)

**Comment by Daztek** [comment]
One left!
