### ISSUE TITLE
Webhook plugin problem (maybe)

### ISSUE THREAD

**Issue by ELadner** [nwnxee/unified#348]
Webhook generates a JSON message like { "text" : "blah, blah, text here" } but Discord, specifically, balks at that.  It expects an element named "content" not "text".

I assume other people are using this with Discord currently.  If so, how?  Any attempt gets a 400 response code and if I test it from the command line with cURL, has the same behavior, but if I change "text" to "content", works like a charm.

```
$ curl -H "Content-Type: application/json" 
    -X POST -d '{"text":"Test Sending"}' https://ptb.discordapp.com/api/webhooks/_channel_/_key_
    
Return 400
Return msg {"code": 50006, "message": "Cannot send an empty message"}

$ curl -H "Content-Type: application/json" 
    -X POST -d '{"content":"Test Sending"}' https://ptb.discordapp.com/api/webhooks/_channel_/_key_
    
Return 200
```

**Comment by Liareth** [comment]
https://github.com/nwnxee/unified/blob/master/Plugins/WebHook/Documentation/README.md

I presume you haven't done this: `Top tip: Append /slack to the end of a Discord webhook url for it to work.`

**Comment by ELadner** [comment]
Nope.  Totally overlooked that.
