### ISSUE TITLE
Feature request: Sun/Moon Ambient/Diffuse Colors

### ISSUE THREAD

**Issue by burmashave** [nwnxee/unified#351]
Is there any way to set these for an area via script or plugin? I know there's a function for fog color, but haven't seen anything for the ambient/diffuse colors.

**Comment by mtijanic** [comment]
Not at the moment, though doable. I'll edit your "question" into a feature request.

**Comment by burmashave** [comment]
Thanks. I'd try it myself if I had any idea how to get started. Is there a 'NWNX Plugins for Dummies' manual floating around?

**Comment by mtijanic** [comment]
This is the closest we have for it I think: https://github.com/BhaalM/stuff/blob/master/simple_nwnxee_tutorial.md

Also, I believe @Daztek is on the case already.
