### ISSUE TITLE
[Request] CheckFreeSpaceFitsInventory

### ISSUE THREAD

**Issue by LiarisFreeze** [nwnxee/unified#362]
CheckFreeSpaceFitsInventory (int Width, int Height)
Function checked the compatibility of the proportions size W and H and free space in inventory for this proportions?

int Width, int Height  i.e. InvSlotWidth and InvSlotHeight in baseitems.2da
To set the required int value.

**Comment by plenarius** [comment]
That'd be `CItemRepository::CheckFit` I believe - can add when I get a chance
