### ISSUE TITLE
Administrator: ResetServer() function

### ISSUE THREAD

**Issue by Alibertos** [nwnxee/unified#38]
To implement really ThreadWatchdog service to reload server when crashes or after admin shutdown

**Comment by Liareth** [comment]
I don't think this is something that should be handled by NWNX (or a plugin of NWNX). I know the old NWNX on Windows used to provide it, but, in my opinion, server maintenance should really be handled by some sort of process watching system which the OS provides.

Here are some potential pages that might help:

https://unix.stackexchange.com/questions/106656/how-do-services-in-debian-work-and-how-can-i-manage-them

https://www.digitalocean.com/community/tutorials/how-to-configure-a-linux-service-to-start-automatically-after-a-crash-or-reboot-part-2-reference

**Comment by Liareth** [comment]
Going to close this issue for the above reasons.
