### ISSUE TITLE
[Request] Add events - on equiped and on unequped

### ISSUE THREAD

**Issue by LiarisFreeze** [nwnxee/unified#386]
Events
ON_EQUIPED_ITEM_BEFORE
ON_UNEQUIPED_ITEM_BEFORE

Cursed items.
Custom features and limit.
Sets.

**Comment by mtijanic** [comment]
Does regular OnEquip not work here? Something like:
```C
            if (should_not_equip)
            {
                AssignCommand(oPC, ClearAllActions(TRUE));
                AssignCommand(oPC, ActionUnequipItem(oItem));
            }
```

**Comment by LiarisFreeze** [comment]
She won't work like that.
The action may cancel or not work.
In addition, events are triggered after the action.
