### ISSUE TITLE
NWNX_Data unexpected behavior

### ISSUE THREAD

**Issue by ELadner** [nwnxee/unified#425]
This seems like it should work, but causes the server to crash (on the very first line).

```
    NWNX_Data_Array_Insert_Str(OBJECT_INVALID, "test", 0, "ALCHEMY");
    NWNX_Data_Array_Insert_Str(OBJECT_INVALID, "test", 1, "ATHLETICS");
    NWNX_Data_Array_Insert_Str(OBJECT_INVALID, "test", 2, "ENCHANTING");
```

It seems like "Insert" expects there to be existing elements around where it's inserting, otherwise, it crashes.

**Comment by Daztek** [comment]
You need to call `NWNX_Data_Array_Resize()` first. It doesn't automatically resize the array.

The following works:

```
NWNX_Data_Array_Resize(NWNX_DATA_TYPE_STRING, OBJECT_INVALID, "test", 3);

NWNX_Data_Array_Insert_Str(OBJECT_INVALID, "test", 0, "ALCHEMY");
NWNX_Data_Array_Insert_Str(OBJECT_INVALID, "test", 1, "ATHLETICS");
NWNX_Data_Array_Insert_Str(OBJECT_INVALID, "test", 2, "ENCHANTING");
```

**Comment by ELadner** [comment]
Thank you, Daz!

**Comment by ELadner** [comment]
Could that insert be made to automatically resize?

PushBack doesn't require manual sizing...

**Comment by mtijanic** [comment]
Fixed in 64bit branch. Closing.
