### ISSUE TITLE
[Request] Add tab-highlighting a switch to Tweaks

### ISSUE THREAD

**Issue by LiarisFreeze** [nwnxee/unified#450]
Is it possible to remove highlighting when you press the tab?

I would like the tab button not to highlight everything.
You can highlight only by hovering the cursor on the creature / object / item.

**Comment by Daztek** [comment]
Hello! Sadly this is not something you can do with NWNX. 

Beamdog has the following Trello card though: [Allow tab-/mouseover-highlight/aura colour customisation through NWScript](https://trello.com/c/kPI65Zgy/62-allow-tab-mouseover-highlight-aura-colour-customisation-through-nwscript), so it might be possible in the future.

**Comment by mtijanic** [comment]
"unlikely" is too generous here. This is simply not something we can do, sorry. Closing.
