### ISSUE TITLE
NWNX:EE-64bit TODO

### ISSUE THREAD

**Issue by Daztek** [nwnxee/unified#459]
### CORE:
  - ~~Add an environment variable(default ON) to disable NWNX calls from ExecuteScriptChunk()~~

### PLUGINS:
- **Administration:**
  - ~~REMOVE: BootPCWithMessage()~~
  - ~~CHANGE: Have OnDeleteTURD() return TRUE on successful deletion~~
  - ~~CHANGE: Clean up the nwnx_admin.nss~~
- **Data:**
  - ~~CHANGE: PR #427~~
- **ELC:**
  - ~~CHANGE: Fix ELC :(~~
- **Effect:**
  - ~~REMOVE: EffectID from Pack/Unpack Functions/Struct~~
- **Events:**
  - INVESTIGATE: Event Name / Event Data Tag standardization.
  - ~~CHANGE: InventoryEvent Event Names, see PR #529~~
  - ~~CHANGE: Refactor `Events.cpp` to be more inline with the other plugins~~ 
- **ItemProperty:**
  - ~~REMOVE: EffectID from Pack/Unpack Functions/Struct~~
- **Mono**
  - INVESTIGATE: Replace Mono with .NET Core or add a separate plugin for it
- **Object:**
  - ~~REMOVE: {Get|Set}EventHandler(), {Get|Set}Portrait()~~
- **Player:**
  - ~~REMOVE: {Get|Set}VisibilityOverride()~~ 
  - ~~CHANGE: Remove the try/catch block around StartGuiTimingBar()'s type variable~~
- **SQL**
  - ~~CHANGE: SQLite currently uses the `.sqlite3` extension, this will conflict with the CampaignDB sqlite implementation. NWNX should use something else.~~
- **Weapon:**
  - INVESTIGATE: Move the Devastating Critical event to NWNX_Events

**Comment by Baaleos** [comment]
Can I suggest that if we do get 64bit support - .Net Core would become a potential replacement for MONO.
This was suggested previously, but the hurdle at the time was that .Net Core was not 32bit capable.

**Comment by mtijanic** [comment]
Yes. Whether it is a replacement or a separate plugin remains to be seen, but it .NET Core support is planned. Mono sucks terribly.

**Comment by jd28** [comment]
Suggestion for nwnx:ee 64: Squash all the namespaces from stuff generated from nwserver into a single `namespace NWN`.  I think everyone can agree that stuff like `NWNXLib::API::Types::ObjectID` is just absurd, it's the most dirt common type in the whole codebase!

**Comment by Liareth** [comment]
Yeah. I dunno what I was doing with that. If I could have a do-over (64-bit API hi) I'd put the API in a `nwn` namespace and core NWNX stuff in a `nwnx` namespace, so `nwn::oid` and `nwnx::Events`. Clearly I was drunk or something when I wrote it.

**Comment by mtijanic** [comment]
How about no namespace for nwn stuff? :)

(I don't think it's a good idea, but it would simplify a lot of things as mangled names would match between nwn and nwnx. I do support nwn/nwnx namespaces)

**Comment by Daztek** [comment]
Preliminary changelog for NWNXEE 64bit

**Added**
*New Plugins*
*New NWScript Functions*
	Data: Array_Set()
	
**Changed**
Administration: DeleteTURD() now returns TRUE on success
Data: Array_Insert() will now actually do an insert instead of a set
Effect: Removed the EffectID parameter from the struct
ELC: Updated with the new ruleset changes
Events: `NWNX_ON_ITEM_INVENTORY_{ADD|REMOVE}_ITEM_*` has been changed to  `NWNX_ON_INVENTORY_{ADD|REMOVE}_ITEM_*`
Itemproperty: Removed the EffectID parameter from the struct
SQL: The SQLite database extension has been changed to `.sqlite3nwnxee`

**Deprecated**

**Removed**
Administration: BootPC()
Experimental: RemoveACABModifiersFromExpertise
Object: {Get|Set}EventHandler(), {Get|Set}Portrait()
Player: {Get|Set}VisibilityOverride()

**Fixed**

**Comment by mtijanic** [comment]
Closing this one since we merged nwnx64.
