### ISSUE TITLE
Config examples?

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#486]
Not all the documentation references configuration values etc
Eg:
[MONO]
key=value 

etc
Was wondering if this is documented anywhere? I have checked the released zips and no nwnx config files seem to be provided.
I am guessing there are meant to be config values for plugins - as some of the source code references key values?

https://github.com/nwnxee/unified/blob/master/Plugins/Mono/Mono.cpp#L82

**Comment by Daztek** [comment]
The various environment variables are generally in the <Plugin>/Documentation folders. The Mono ones are at the bottom of its documentation readme, they should be prefixed with NWNX_MONO_ though.

You can set em like this: `export NWNX_MONO_ALLOW_REMOTE_DEBUGGING=true` etc

**Comment by Baaleos** [comment]
ah - my bad - I was still expecting it to look for a nwnx.ini - like 1.69
