### ISSUE TITLE
[BUG] `RemoveEffect` doesn't trigger effect events

### ISSUE THREAD

**Issue by weavejester** [nwnxee/unified#501]
When the `RemoveEffect` function is called to remove an effect, the `NWNX_ON_EFFECT_REMOVED_BEFORE ` and `NWNX_ON_EFFECT_REMOVED_AFTER` events are not triggered.

It looks like the `OnEffectRemoved` event is only triggered when an effect ends naturally, not when it is removed by a script.

**Comment by Daztek** [comment]
Should be fixed with #506
