### ISSUE TITLE
Question: Persistent player id's without storage object?

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#510]
So one of the things that many PW servers will need to implement for their own internal systems is some sort of unique id system for players.
Eg: in case a player creates another character of the same name etc.

The only way in 1.69 I could think of to store the player ID persistently was an object that could be stored in the players inventory that could not be removed / dropped.
This would then link up to a persistent ID that is in the database also - and allows the ID to be reloaded on character login etc after resets.

My question here is: 
Does there exist any possibility of adding small amounts of data to the Bic files directly via nwnx - so we don't have to use a storage object?
Storage objects are vulnerable to DM tampering etc - a DM could remove it on purpose or accidentally etc.

Eg: What if a unique ID was added to the level-stats (level 0) - for a player.
Would that make their BIC file invalid?

If anyone has any ideas - interested to hear.

**Comment by mtijanic** [comment]
Just store it in the player's tag with the `SetTag()` function. No NWNX required, persists to bic.

**Comment by Baaleos** [comment]
Ah... didn't know SetTag worked on players.
Fair enough...
