### ISSUE TITLE
Error in Plugins/Creature/Creature.cpp

### ISSUE THREAD

**Issue by BhaalM** [nwnxee/unified#55]
Line 509:
const auto offset  = Services::Events::ExtractArgument<int32_t>(args); assert(value <= 255);

Should be:
const auto offset  = Services::Events::ExtractArgument<int32_t>(args); assert(**offset** <= 255);

Thank you for your work!

**Comment by zunath** [comment]
Thanks - I'll fix this tomorrow.

**Comment by Liareth** [comment]
This wasn't hitting CI because CI builds without asserts. I fixed it in 46aec42a47ecae8fc7519c9233652dd7ebf22c13.
