### ISSUE TITLE
NWNX_Damage_DealDamage - Ranged/Melee/Misc

### ISSUE THREAD

**Issue by FrogsOfDoom** [nwnxee/unified#553]
Hi,

When using this function in our PW, I realized there was no way to indicate how the damage was dealt; it seems to default to melee damage. This is a problem with damage shields (Mestil's, Fire Shield, etc.) since even if used in a spell (ie: Evard's) or a ranged weapon, it will trigger the damage shield's damage event and thus damage the effect creator.

It'd be great if we could indicate the type of damage (ie: Ranged, Melee, Misc). Is this feasible?

Thanks

EO

**Comment by mtijanic** [comment]
FYI, `eff->m_nParamInteger[18]` is `bRangedAttack`, so just need to set that one.

**Comment by GideonCrawle** [comment]
This has now been added as a flag in NWNX_Damage_DealDamage().
