### ISSUE TITLE
Error in Plugins/Chat/Chat.cpp

### ISSUE THREAD

**Issue by BhaalM** [nwnxee/unified#56]
Line 49
m_chatScript = GetServices()->m_config->Get<std::string>("CHAT_SCRIPT", "");

Should be (?)
m_chatScript = GetServices()->m_config->Get<std::string>("SCRIPT", "");

**Comment by Liareth** [comment]
This was actually intended - it used to take CHAT_SCRIPT and SYSTEM_SCRIPT. Chat used to dispatch to two separate scripts, depending on whether the messages were being sent to the system window or actually chat messages. Now you just tell that based on the chat channel - so it only supports one script. If this is a big deal we can make it check for SCRIPT if CHAT_SCRIPT isn't defined.

**Comment by BhaalM** [comment]
No, no, it's ok! 

It's just that when I first used the plugin I exported the variable "NWNX_CHAT_SCRIPT" and it didn't work. When I looked to the source code it seemed to me somewhat strange to have to export "NWNX_CHAT_CHAT_SCRIPT" and I thought it was a "bug", but now I see that it's a "feature" :D 

Thank you and sorry for opening this issue!
