### ISSUE TITLE
Feature Request: Hide/Show PlayerName 

### ISSUE THREAD

**Issue by Christian-Vassallo** [nwnxee/unified#563]
Hello guys,

In some server there are disguise systems that are amazing but they have one problem: clicking on the portrait (chat window) or at the enter/exit, the account name is visibile.

Then, somehow, the systems of disguise have a weakness point. 
In order to improve the RPG experience on the servers could be nice to have this tweak: not only the name of the PC can be hidden but also the account.
Perfect would be to have “hidden” or “visibile” for specific target.
In this way not all the playernames would be hidden but only for who desires.

Something like:
SetPlayerNameVisible(oPC, true/false)

What do you think?

**Comment by Daztek** [comment]
I believe NWNX_Rename already does that?

```

//Set a PC's floaty/chat name(sPrefix+sNewName+sSuffix) and name (sNewName) on the player list.
//If a target is specified, the PCs name will appear to that target as set, this overrides a global setting.
//If (iPlayerNameState) is set to NWNX_RENAME_PLAYERNAME_OVERRIDE the player name will change to (sNewName) on tells.
//If (iPlayerNameState) is set to NWNX_RENAME_PLAYERNAME_OBFUSCATE the player name will be set to a random string.
//If (iPlayerNameState) is set to NWNX_RENAME_PLAYERNAME_DEFAULT the player name will be untouched.
//DMs and the player themselves will still see their original player name regardless of option set
//Will not persist through saving, resets or logout.
void NWNX_Rename_SetPCNameOverride(object oPC, string sNewName, string sPrefix = "" , string sSuffix = "" ,
                                   int iPlayerNameState = NWNX_RENAME_PLAYERNAME_DEFAULT, object oTarget=OBJECT_INVALID);```

**Comment by Christian-Vassallo** [comment]
I was thinking that Rename was for Name PC.

Example: metagamer login with the character Micky Mouse.

I understood that with Rename plugin I could set the character name Micky Mouse to Mr Rabbit. Like plugin Name was doing in 1.69

Maybe is it the opposite? argh.

**Comment by plenarius** [comment]
It does both.

The option to NWNX_RENAME_PLAYERNAME_OBFUSCATE is what you're looking for.

`NWNX_Rename_SetPCNameOverride(oPC, "Disguised PC", "" , "" 
,NWNX_RENAME_PLAYERNAME_OBFUSCATE);`

This would change PC name to `Disguised PC` and the PlayerName to like `zyxfgdzr`

**Comment by Christian-Vassallo** [comment]
Amazing :)

Thank you so much
