### ISSUE TITLE
Plugin Folder Structure

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#573]
What is the point of all the plugin readme's tucked in to a documentation folder?  Half of them are just stubs.  It seems contrary to how github works.  You click a folder you get documentation for that folder.  There doesn't seem to be any wiki or auto-generated docs.. or am I missing something?

**Comment by jd28** [comment]
Is anyone opposed to plugin readmes being in the plugin's folder?  I'm happy to do this and expand documentation as needed.

**Comment by mtijanic** [comment]
Go for it.
