### ISSUE TITLE
[Suggestion] Awesome NWNX

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#574]
I'm sure most people on here are familiar with the awesome-X lists.  It would be neat if there was a a curated list on here of cool stuff people are _actually_ doing with these plugins and nwnx.

**Comment by mtijanic** [comment]
A related idea would be a new repo (under nwnxee/) that uses @Daztek 's event setup as a base, and then people can add their own little systems as single files. Can serve as a primer and a test suite for NWNX too.

**Comment by jd28** [comment]
Sounds like a great idea to me!  Anything that gets more people engaged and interested is tops in my opinion.
