### ISSUE TITLE
[Bug] NWNX_Effect_UnpackEffect crashes server when used to unpack a linked effect

### ISSUE THREAD

**Issue by Tildryn** [nwnxee/unified#594]
As above, when NWNX_Effect_UnpackEffect is used on an effect that has been linked to any other effects, the server crashes entirely.

**Comment by mtijanic** [comment]
Crash log, please? :)

**Comment by Tildryn** [comment]
[nwserver-crash-1570362988.log](https://github.com/nwnxee/unified/files/3694380/nwserver-crash-1570362988.log)

**Comment by plenarius** [comment]
This appears to be a result of this change https://github.com/nwnxee/unified/commit/31aeaaf1f058041be3f706161a0a095d488ed56b

The `DestroyGameEffect` destroys the linked effects as well. 

I'm not really sure the best course of action. Should we copy the linked effects to their own and return those new ones with the unpack? Something like (tested and working):
```cpp
    if (eff->m_pLinkLeft != nullptr)
    {
        auto *leftLinkEff = new API::CGameEffect(true);
        leftLinkEff->CopyEffect(eff->m_pLinkLeft, 0);
        Services::Events::InsertArgument(stack, (API::CGameEffect*)leftLinkEff);
    }
    else
    {
        Services::Events::InsertArgument(stack, (API::CGameEffect*)nullptr);
    }
    Services::Events::InsertArgument(stack, (int32_t)(eff->m_pLinkLeft != nullptr));
```

Or perhaps there is a way to decouple the linked effects before the `DestroyGameEffect` that I'm not seeing?
