### ISSUE TITLE
Possible nullptr derefrences

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#602]
https://github.com/nwnxee/unified/blob/a33e5c78fa091511a7fa83bc6150e0a378ee060f/Plugins/ELC/ELC.cpp#L414-L434

I don't know anything about this plugin.  Maybe this all fine, but there is on it's face a possibility for nullptr dereference here.  it probably all works cause it can't not work, but it's not obvious.

**Comment by jd28** [comment]
Same is true here: https://github.com/nwnxee/unified/blob/8eab310bcd358541879844f1fec48372286a74c5/Plugins/ELC/ELC.cpp#L969-L984

**Comment by Daztek** [comment]
Yeah, there's a nullptr dereference chance if a builder opts to skip that validation failure on the nwscript side, I should probably just straight up return in those cases.

**Comment by Daztek** [comment]
Closing this for now, since the chance is super low and the builder specifically has to skip those failures.
