### ISSUE TITLE
[BUG] NWNX_Event : NWNX_ON_MAP_PIN_ADD_PIN_BEFORE/AFTER

### ISSUE THREAD

**Issue by OrdalieNWN** [nwnxee/unified#603]
Hello, It seems that "NWNX_Events_GetEventData("PIN_ID")" doesn't work in this two event 

It works great in MAP_PIN_CHANGE and DELETE 

Here is the code i use in the event script 👍 
`    object oPC = OBJECT_SELF;

    int nPinNum = StringToInt(NWNX_Events_GetEventData("PIN_ID"));
    string sName = NWNX_Events_GetEventData("PIN_NOTE");
    float fXPOS = StringToFloat(NWNX_Events_GetEventData("PIN_X"));
    float fYPOS = StringToFloat(NWNX_Events_GetEventData("PIN_Y"));
    object oArea = GetArea(oPC);

    //Debug
    SendMessageToPC(oPC, "PinNum: "+  NWNX_Events_GetEventData("PIN_ID") +"\n PinX: " + NWNX_Events_GetEventData("PIN_X") + "\n PinY: " +
                                        NWNX_Events_GetEventData("PIN_Y") + "\n PinName: " + NWNX_Events_GetEventData("PIN_NOTE"));
    SendMessageToPC(oPC, "NWNXPINID_ADDAFATER: " + NWNX_Events_GetEventData("PIN_ID"));`

Other Data works good too

**Comment by OrdalieNWN** [comment]
(not a real issue i think, as i can get the pin number with GetLocalInt(oPC, "NW_TOTAL_MAP_PINS") in the "AFTER" event, the pin added was obviously the last one, but don't kwon if you wnat to fix it)

**Comment by plenarius** [comment]
I'm afraid the PIN_ID is not available in the NWNX_ON_MAP_PIN_ADD_PIN_* events. The method you are using is the means to acquire it. I'll update the documentation to indicate such.
