### ISSUE TITLE
Should Event documentation be separated from the nss?

### ISSUE THREAD

**Issue by plenarius** [nwnxee/unified#608]
I figure it would make more sense for available events to be organized and documented better than as a massive comment in the start of the nss.

**Comment by Daztek** [comment]
It'd be neat if they had their own page on the new docs website, imo.

**Comment by jd28** [comment]
It would be nice if the `Documentation | <X> Reference` and the `Plugins and Core Lib Functions | <X>` could somehow be merged together.  Dunno if that's possible or if it relates to this issue.  I think there should be one page per plugin and core to know everything one needs to know.

**Comment by mtijanic** [comment]
Can we leave the massive comment in nss, but format it such that it shows up as its own page in the generated docs? I'd expect there to be people that prefer to stay in the toolset and have access to all the needed info.

**Comment by plenarius** [comment]
This was addressed in #659
