### ISSUE TITLE
Docs: Combine README and nss API in single page

### ISSUE THREAD

**Issue by plenarius** [nwnxee/unified#615]
It would be nice if the `Documentation | <X> Reference` and the `Plugins and Core Lib Functions | <X>` could somehow be merged together.  Dunno if that's possible or if it relates to this issue.  I think there should be one page per plugin and core to know everything one needs to know.

_Originally posted by @jd28 in https://github.com/nwnxee/unified/issues/608#issuecomment-542043634_

**Comment by jd28** [comment]
I'm just gonna amend my comment that core services should be separated out to respective pages, with clear usage.  There's a too much copy and paste going on.  Just for example, nwnx_data is not hot-swappable, supposing that functionality existed, yet it returns true for that Plugin::Info parameter anyway.

**Comment by plenarius** [comment]
The core functions are already separated into their own page? 

I'm a bit confused. What you're bringing up seems rather completely separate from the issue? You're asking for better documentation and greater thought/understanding put into documenting and coding new plugins.

**Comment by jd28** [comment]
Yes, I apologize, different issue.  Sorry for the confusion, please disregard it.
