### ISSUE TITLE
plugins/data: Should probably be backed by POS

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#616]
Since it kinda coalesces with some comments I've made on other issues, the data plugin should probably use the POS infrastructure for storing it's data.

**Comment by jd28** [comment]
This would be pointless, if the whole idea of hot reloading is dropped.  So it depends on #637 .

**Comment by mtijanic** [comment]
I'm going to close this, since we exposed POS directly. People can just use POS instead of nwnx_data if it suits their purpose.
