### ISSUE TITLE
Upgrading GCC in Docker to at least version 7

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#625]
Was mentioned in passing in Discord, I don't know enough about Docker to know what's feasible.

**Comment by jakkn** [comment]
It's a very simple change, buping 6 to 7 on these lines https://github.com/nwnxee/unified-docker-builder/blob/b30b5724a47972ce68adfd48c5a06198ac78b6d0/Dockerfile#L8-L9

Has gcc-7 been tested to work fine?

**Comment by Daztek** [comment]
Should be fine, you'll also need to change it from debian stretch to debian buster since stretch doesn't have gcc7 iirc.

**Comment by jakkn** [comment]
https://github.com/nwnxee/unified-docker-builder/pull/1
