### ISSUE TITLE
[Idea/docs] Use something like contributor-faces in the main readme

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#628]
https://github.com/ngryman/contributor-faces

I've seen a lot more github projects these days using something like this.  i think it might be cool to replace the "who makes nwnx:ee?" section with this.

**Comment by mtijanic** [comment]
Don't take this the wrong way (I certainly do value the contributors and am open to new ways of recognizing them), but I'm personally not a fan of too much bling in the readme. 

Ideally it should be easily readable as plaintext and contain only the actually useful things, with links for further reading. We already have too much crap there IMO.

As for contributor faces, github already has that in a dedicated little section: ![](https://i.imgur.com/zLUlLVm.png)

so if we're gonna add some kind of credits section, let's make it something that's not just a bigger version of that.

**Comment by jd28** [comment]
After looking more into it, I really didn't think it was worth the effort either.  So I'm closing.
