### ISSUE TITLE
[new plugin] .NET Core

### ISSUE THREAD

**Issue by mtijanic** [nwnxee/unified#634]
Since we got rid of mono, and since we're at 64bit now, we can finally add a proper .NET core runtime.

(I'll be handling this, just wanted an issue here for a public record)

**Comment by zunath** [comment]
Super excited for this. Can I ask if you'll continue to use the same C# API as what was in the Mono plugin? Trying to get the scope of the changes involved.

**Comment by mtijanic** [comment]
Yes, the `NWScript` class API will remain as is. Probably the implementation too, and only the `Internal` classes will change.

The only breaking change planned from the API point of view is the single entry point. There's probably going to be other incompatibilities in the various other dependencies though.

**Comment by Visavant** [comment]
How will major releases be handled or will you follow LTS patterns?

**Comment by mtijanic** [comment]
>How will major releases be handled or will you follow LTS patterns?

We'll use 3.1 LTS (to be released December) for the foreseeable future.
