### ISSUE TITLE
Plugin hot reload

### ISSUE THREAD

**Issue by mtijanic** [nwnxee/unified#637]
(Originally mentioned in #6 )

It'd be nice if plugins could be hotswapped while the core is still running, for quick updates and whatnot. The core architecture already has this in mind, but there's a bunch of smaller kinks to work out before it is feasible, so marking 'unlikely' for now.

**Comment by jd28** [comment]
Personally never thought it was worth the added infrastructure to make it possible back when this was a 1.69 thing.  POS helps a lot.  Some plugins simply can't be hotswapped (scripting engines), other scenarios require the hotswapping of the plugin and their respective nwscripts at the same time.  That then raises the question of what happens during a DelayCommand and hotswaps?  Imo, it's just not worth it.

**Comment by mtijanic** [comment]
The biggest use for hotswapping is probably loading the Profiler only when you actually need it, but that can be handled with switches and commands in the profiler itself.
A distant second usecase is updating stateless plugins (e.g. object/creature/item/admin/etc), but that's so rare that you can go with a restart as well..

I'll add the RFC tag here for now, in case someone else has a good usecase. If not, I'll close this, add switches to the profiler, and remove the extra infra that's there for hotswapping.

**Comment by jd28** [comment]
I never even considered the profiler use case, I figured since it was built around Influx anyone that wanted to use it would have it on all the time.

**Comment by mtijanic** [comment]
Close as WNF. Pretty useless feature.
