### ISSUE TITLE
NWN_Object crash

### ISSUE THREAD

**Issue by driller-nwn** [nwnxee/unified#67]
When you attempt to use the NWNX_Object_Deserialize or NWNX_Object_Serialize function, it causes nwserver to crash with a segmentation fault. This appeared after the 8164 update.

**Comment by Liareth** [comment]
I've pushed a speculative fix, I can't test it right now but I'm hoping it helps. Can you try https://github.com/nwnxee/unified/commit/a3f2e51cc71b0dd74b0569775f8c4b29ecf4df0b please?

**Comment by Liareth** [comment]
This was actually caused by the new logging system - NWNX_CORE_LOG_LEVEL=7 caused a massive object to be printed, writing over the max buffer length. @mtijanic kindly fixed it. You can work around it without any binary changes by lowering the log level.
