### ISSUE TITLE
Add current script name to some error prints

### ISSUE THREAD

**Issue by mtijanic** [nwnxee/unified#684]
Updating the nwnx nss files, but not doing a full module rebuild seems to be a common issue. People are then greeted with semi-cryptic message of

    Plugin 'NWNX_Events' does not have an event 'SUBSCRIBE_EVENT' registered

We should add the name of the script making the request to the print, and a note saying "are your nwnx_*.nss files up to date?"

**Comment by Daztek** [comment]
This error message also shows if the plugin isn't loaded, it'd be nice if we check for that too.
