### ISSUE TITLE
BUG: Crash when NWNX_CORE_SKIP=Y

### ISSUE THREAD

**Issue by nwngracken** [nwnxee/unified#70]
I'm consistently crashing when loading the DockerDemo module that comes inside the nwnxee/nwserver:8164 docker container (https://hub.docker.com/r/nwnxee/nwserver/). NWNX_Core.so is being preloaded, but it's being skipped with the NWNX_CORE_SKIP=Y environmental variable, which is set in the attached [config.txt](https://github.com/nwnxee/unified/files/1821672/config.txt) file that contains the environmental variables passed to docker (with --env-file).

This crash does not happen when NWNX_Core.so is not LD_PRELOAD'ed.

This crash does not happen if NWNX_Core.so is LD_PRELOAD'ed and NWNX_CORE_SKIP=N

I've attached [nwserver-crash-1521259791.log](https://github.com/nwnxee/unified/files/1821663/nwserver-crash-1521259791.log).

**Comment by mtijanic** [comment]
I guess it should fail gracefully instead of crashing, but.. what's the use-case of skipping the core?

**Comment by nwngracken** [comment]
There isn't one necessarily.  I did it while debugging another crash issue.  I'd think using NWNX_CORE_SKIP=Y would be a good way to turn off NWNX without removing NWNX_Core.so from LD_PRELOAD.

**Comment by mtijanic** [comment]
Ack, good point, for some deployments removing the preload might be a hassle. Thanks.

**Comment by Liareth** [comment]
Fixed in 8164-1.
