### ISSUE TITLE
settings.tml link issue

### ISSUE THREAD

**Issue by driller-nwn** [nwnxee/unified#705]
If nwserver restarts, it will not load and exits with this error. Removing settings.tml allows the server to run again.

nwserver_1  | [*] Linking in settings.tml
nwserver_1  | ln: failed to create symbolic link '/nwn/run/settings.tml': File exists
nwn_nwserver_1 exited with code 1

**Comment by Daztek** [comment]
What docker tag are you using, and how are you starting your server?

**Comment by driller-nwn** [comment]
Using this with docker-compose. 
https://github.com/urothis/nwnxee-docker-template/blob/master/docker-compose.yml

The tag is: nwnxee/unified:latest

**Comment by Daztek** [comment]
I think I've fixed it, can you do a `docker pull nwnxee/unified:latest` and see if it's fixed?

**Comment by driller-nwn** [comment]
This is fixed. Thank you.
