### ISSUE TITLE
[Races] suggestion : per race hooks/scripts

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#735]
For example- having a death script for a vampire as opposed to a human etc
It's certainly achievable without modifying the races plugin - but it might be a nice addition as it would make the races plugin a step closer to providing the sorts of things most subrace systems would need - e.g.: handlers for events specific to races.

Some prototypes i was thinking of:
SetRacialEvent(int race, int eventType, string script)
RemoveRacialEvent(int race, int eventType)
CallBaseEvent(); // used to call the module default event and then return to the the calling script
Use case for base event would be so you define the basic death event as a module script - this covers functionality that happens for all races - so in your racial death event you call 'CallBaseEvent' to execute the base  - before applying the say.. vampire death script.
It would be the equivalent of calling base or super in .net or java.

Other possible cases could be to have heartbeat scripts for specific races etc

**Comment by mtijanic** [comment]
Doing this through nwscript is a whole lot more flexible, and there's no real penalty to pay as well. You can use SetEventScript() to set creature events for the PC, so just do something like:

```C
void SetRaceHB(object oPC) {
    string script;
    switch (GetRacialType(oPC) {
        case RACIAL_TYPE_VAMPIRE: script = "hb_vampire"; break;
        case RACIAL_TYPE_LYCANTHROPE: script = "hb_lycan"; break;
        ...
    }
    SetEventScript(oPC, EVENT_SCRIPT_CREATURE_HEARTBEAT, script);
}
```
You can even use the nwnx_events infrastructure to signal and subscribe to the events.

If there's anything that is exceptionally difficult or slow to do in nwscript, that should go in nwnx, but that means trading flexibility for functionality (or speed in some cases).
