### ISSUE TITLE
Question around dotNet plugin

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#738]
Coming from using nwnx_dotnet - where it allowed you to execute .net code via targeting an assembly, class and method - and then get a return object. 
This approach seems a little different from the implementation of the dotnet plugin in unified.

Can someone confirm the following.

1. The OnRunScript event - the documentation says that it runs before every script is executed.
    Am I able to build a script entirely in .net code and have it exist in the assembly - without having to have a nss / ncs script in the module/haks?  Eg: Can I do the following.
ExecuteScript("set_variables",OBJECT_SELF);  
Without having a set_variables nss/ncs file in the module - and instead handle the entire script in .net code.

2. Do we know if threading is safe - as long as we have no intention on returning to the NWScript context? Eg: Having a hb built in .net core which just increments static numbers - and then have those numbers accessed and referenced from other NWScript context scripts?

3. Is there anyway to pass parameters to the .net code from NWScript in game?
Eg: One of the things I did previously was make it possible to call an Email function to email players.

EmailPlayer(string emailAddress)

Would I have to set emailAddress as a local variable in a nss/ncs - and then read from that local in the .Net based OnRunScript - in order to extract the variables?

Thanks in advance - I've been looking forward to using dotnet core on NWN - Just need to get used to the different way of operating etc.

**Comment by mtijanic** [comment]
1. Yes. You can have an entire module in dotnet without any ncs files existing if wanted.

2. You can have multiple threads, as long as none of those threads make any nwscript or nwnx calls. So, a side thread that modifies shared data and a main thread that reads it is okay. You might still need to have synchronization between these threads, if the shared data is more complex than an integer.

3. No way to directly pass data. You can have nwscript write locals and dotnet read them, like you mention. You could use stuff like `NWNX_Object_SetXxx()` or something, but no way to directly pass it.

Cheers!

**Comment by mtijanic** [comment]
Closing as non-actionable. Feel free to reopen if the answers given are incomplete.
