### ISSUE TITLE
NwNx_Creatures - Update functions for Schools/Domains (8193.6 and +)

### ISSUE THREAD

**Issue by FrogsOfDoom** [nwnxee/unified#742]
Hi,

Since patch 8193.6, any class can now have Domains and a School of magic, but NwNx_Creatures at the moment only looks for these variables under the Cleric/Wizard classes. Could the following functions be updated to allow us to input the Class?

int NWNX_Creature_GetClericDomain(object creature, int index);
void NWNX_Creature_SetClericDomain(object creature, int index, int domain);
int NWNX_Creature_GetWizardSpecialization(object creature);
void NWNX_Creature_SetWizardSpecialization(object creature, int school);

Thanks!

**Comment by GoLoT** [comment]
Quick fix in #743 pending testing.
