### ISSUE TITLE
NWNX_TWEAKS_SNEAK_ATTACK_IGNORE_CRIT_IMMUNITY - No Flanking Sneak/Death attacks while enabled

### ISSUE THREAD

**Issue by TomRotfl** [nwnxee/unified#747]
Noticed since `NWN:EE build 8193.4` (never tested it on previous releases)

- Enabling `NWNX_TWEAKS_SNEAK_ATTACK_IGNORE_CRIT_IMMUNITY `makes both creatures and players unable to land Sneak/Death Attacks while flanking an opponent.
- Only flat-footed creatures/players can be subject to Sneak/Death Attacks while this Environment Variable is enabled.
- Disabling it restored the default situation and both creatures and players were able to Sneak/Death attack while flanking.

**Comment by mtijanic** [comment]
Are you compiling NWNX  from source? Think you could take #748 for a spin?
If not, we can merge and then give it a try?

**Comment by TomRotfl** [comment]
I use docker on linux. currently running 8193.5 (latest of this branch). 

Any specific instruction to test this? Can i test being still on 8193.5? id like not to upgrade yet.
Removing/recreating the container is enough?

Thank you and sorry for all the questions.

**Comment by GoLoT** [comment]
You need to merge that specific commit and compile NWNX yourself if you want to try it on 8193.5.

Why are you hesitant to update to 8193.6? There might be minor issues with the new features but it should be working fine for the most part.

**Comment by TomRotfl** [comment]
I tried like 2 days ago to upgrade the server to 8193.6 and many players with a caster character were unable to login due to failed ELC check (some error about having too many spells). I don't have any custom spells/class specific 2da in my server override folder and i am not using haks.
