### ISSUE TITLE
Docker build doesn't seem to be working on windows

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#759]
Realise that the preferred way is native linux.
Unfortunately I am stuck with a windows 2012 server and I am trying to get Jenkins hooked up to build nwnx plugins.

Current setup is using Docker Toolbox for Windows

When I execute the rundockerbuild.ps1 file
I am given :
Error response from daemon: invalid mode: /nwnx/home.

Research has told me that the $PWD command is passing in the fully qualified directory on windows - this results in you getting a valid of c:\Program Files\Jenkins\Workspaces etc

The issue here is that docker does not like having two :  (colon) characters provided at this point.

However, in my tests, I have also attempted to manually change the ${PWD} to be the linux notation of a locally shared folder 
Eg: Further research told me that I needed to go into VirtualBox - which is where the linux guest is running, and share a local drive
Eg: C:\server
becomes //c/server - in theory.

Anyway... after all my testing - I now get 
/bin/bash: /nwnx/home/Scripts/buildnwnx.sh: No such file or directory

Can anyone else confirm if they are able to build using Docker Toolbox for Windows?
Maybe it is working fine on Docker Desktop for Windows

At the very least- there may be an incompatibility with the ${PWD} on windows - since windows directories are going to have the colon character.

**Comment by Baaleos** [comment]
C:\Program Files (x86)\Jenkins\workspace\nwnx-build\Scripts>Powershell -file rundockerbuild.ps1 -JOBS 6 
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid mode: /nwnx/home.

**Comment by Baaleos** [comment]
Closing - as prob more to do with my setup than anything- in the end I built it all via virtual box etc

**Comment by urothis** [comment]
Can confirm, was able to compile using Docker Desktop and WSL2.
