### ISSUE TITLE
Setting Item Charge Max to 50

### ISSUE THREAD

**Issue by Balanor** [nwnxee/unified#761]
Spoke with sherincall on the NWNX Discord, and he mentioned it might be possible for NWNX to set the item charge limit back to 50. This would be nice for servers relying on the old calculation of an item's value and/or for those relying on the value that is shown for these items as calculated in the toolset at the moment.

Example: In the toolset, an item with 15 charges that has Cast Spell: Gate (17) 5 Charges/Use shows as a value of 51638 which is an ILR of 16. But when created in-game it has a value of 3099 and an ILR of 4.

**Comment by mtijanic** [comment]
I think it will be enough to just sharedhook `CNWSItem::CalculateBaseCosts()` like:
```c
if (before) pThis->m_nNumCharges *= 5;
else pThis->m_nNumCharges /= 5;
```

**Comment by GoLoT** [comment]
I'm taking a different approach rewriting 'CNWSItem::CalculateBaseCosts()'. So far I added 3 options and I'm working on the 4th:

- Cap item cost to 50 charges. Any extra charges over 50 won't add extra value.
- Use 1.69 costs for up to 50 charges and increase the cost linearly after that to twice as much (when at 250 charges). This avoids having extremely overpriced items.
- Calculate costs using 50 as the charge limit. This should behave like the proposed solution but it will make 250 charge items cost 5 times as much as a 50 charge item.
- Call a user defined nwscript.

I guess I could add an extra option to use exclusive hooks as suggested so it doesn't break if the original code is changed.

WIP: https://github.com/GoLoT/unified/blob/chargecost/Plugins/Tweaks/Tweaks/ItemChargesCost.cpp
