### ISSUE TITLE
NWNX_Object{Get|Set}{Int|String} NOT persistent on bic file

### ISSUE THREAD

**Issue by TomRotfl** [nwnxee/unified#764]
So here is the thing:
PW, Servervault.

I used to replace some MySQL persistent variables from the DB to the .bic files directly.

Using a function like: 

`object oPC = GetEnteringObject();
NWNX_Object_SetInt(oPC , "VAR_NAME", int, TRUE);`

That functions fires on the player joining and fires only after he has loaded a valid area.
After i've set my variable (grabbing it from MySQL before), i fire `ExportSingleCharacter(oPC);`

IF, the server crashes OR if i just close the server with `exit` on console, on next login the variable is gone.

So i don't know if this is a `ExportSingleCharacter(oPC)` issue or something about `NWNX_Object_SetInt` not working properly.

I haven't tested with float values.

**Comment by TomRotfl** [comment]
@Daztek did some testing and looks like that only the `exit` command reproduces the bug, not a server crash. Then i don't know if that's possible to patch.

**Comment by GoLoT** [comment]
Apparently the POS is saved to the bic file in `CNWSUUID::SaveToGff()` (using a shared hook) which is called by `CNWSCreature::SaveCreature()`. When `exit`ing the server players are booted but the `CNWSUUID::SaveToGff()` hook isn't being called. I don't know if that's the actual issue, just pointint it out.

**Comment by mtijanic** [comment]
IIRC exit command will not save characters properly anyway. Which is why you should always boot players before shutting down the server.

If someone wants to tackle fixing this, I think there's a lot more to it than just POS

**Comment by TomRotfl** [comment]
That's fine, i just wanted to let you know it could happen. I usually don't kill the server with the `exit` command, but since it happened i thought it was good to signal it.

Does removing and recreating the container on Docker could cause some similar issues? (After i have booted all players and shutdown the server with `NWNX_Administration_ShutdownServer();`

Just asking since i was pretty sure i had booted everyone prior to kill the container but on next login some players had missing variables.

**Comment by GoLoT** [comment]
After doing some digging into the issue I found that using the `exit` or `quit` command simply sets a global flag (0xbd9098) that breaks the main loop and immediately calls `CAppManager::DestroyServer()`.

The command is processed in a function that's called at the end of the loop, causing the loop to break as soon as that function returns. The only function that is called after setting the flag and before breaking the main loop is `CExoCriticalSection::LeaveCriticalSection()`. Hooking that and checking the exit flag could work for disabling the exit/quit commands or handling the exit more gracefully, but the global isn't exposed to NWNX so it would be a platform and version dependent solution.

The next best thing would be to hook (shared, before event) `CAppManager::DestroyServer()` and force a character save on all players or do whatever needs to be done. I don't think this is something that needs to be fixed considering exit is doing what's supposed to do and there are ways to quit gracefully and/or save characters before calling exit. Just leaving it here in case someone wants to use exit and still force a character save.

**Comment by Daztek** [comment]
`DestroyServer()` already has an exclusive hook in Core and saving characters in the shutdown script doesn't seem to work, I guess ExportCharacter queues it for some point after the script runs, in which case it never runs because it kills the server shortly after.

**Comment by GoLoT** [comment]
Yeah, that's probably the case.

I can think of 2 solutions: Rewriting the save function that is called when the save command is used (it's a small and straightforward function that should be easy to rewrite) or faking one last MainLoop iteration, which basically calls `CServerExoApp::RunModule()` if  `CServerExoApp::GetServerMode()`returns 1, and then calls `CServerExoApp::MainLoop()`.

So... adding those 2 calls to `DestroyServerHandler()` before the `app->DestroyServer()` should do the trick, and it's the easiest to implement. The RunModule() call probably isn't needed.

**Comment by mtijanic** [comment]
It should be enough to just call `CServerExoAppInternal::ExportAllPlayers()` in there somewhere. Maybe a shared hook on `CServerExoApp::MainLoop()`, that just does:
```c
if (*Globals::ExitProgram()) pThis->ExportAllPlayers();
```

This should however be a Tweak, as it changes default behavior regardless of POS.

**Comment by GoLoT** [comment]
In my opinion one last MainLoop iteration before destroying the server shouldn't have a negative effect and would help with this issue and possibly some similar issues, while being transparent to users, avoiding having to create a new plugin and also being the expected behavior when trying to save characters from a shutdown script.

**Comment by mtijanic** [comment]
I'm not a fan of running an extra iteration as that can easily have unintended consequences - in fact I'd be surprised if it _didn't_ break any obscure thing. Much better to focus the change on what is actually broken (or "broken"). 
Besides, with the extra iteration, you still need to manually call ExportAllCharacters() in the shutdown script. IMO, if we want to fix the issue of characters not saving on server exit, it should be a tweak that just exports all characters, as if they were booted first.

**Comment by GoLoT** [comment]
What about
```cpp
if(app->m_pServerExoApp->m_pcExoAppInternal->m_bExportCharacterPending)
    pThis->ExportAllPlayers();
```
right after the shutdown script call in `NWNXCore::DestroyServerHandler()`?

It seems like a good compromise, allowing exporting characters from the shutdown script and without having to create a new plugin/hook.

**Comment by mtijanic** [comment]
Good idea!

**Comment by Daztek** [comment]
Doesn't seem to work, it seems to save everything but the POS stuff regardless of adding an ExportAllCharacters. I think the issue lies elsewhere, possibly in POS itself.

**Comment by GoLoT** [comment]
Did you put the `pThis->ExportAllPlayers();` call before or after `g_core->Shutdown();`?

If the bic files are being saved it should be working because `SaveCreature()` calls `CNWSUUID::SaveToGff()` (where POS is persisted), unless the hooks are removed already at that point.

**Comment by Daztek** [comment]
Right after the `ExecuteScript()` call, I had an `ExportAllCharacters` in my shutdown script and `m_bExportCharacterPending` returned true.

**Comment by GoLoT** [comment]
That's odd. I'm doing static analysis but I can't see why it isn't calling `CNWSUUID::SaveToGff()`. There are no conditional jumps or anything that would avoid calling the function. I'm out of ideas for now, I guess I'll need to do dynamic analysis to see if I can track it down.

**Comment by Daztek** [comment]
Odd thing is, even without that addition to the DestroyServer hook and no ExportAllCharacters in the shutdown script, it does save the character's UUID if you do an `exit`

**Comment by Daztek** [comment]
Looking into it some more, `CAppManager::DestroyServer()` does save all characters, but it rebuilds the bic file from scratch. As NWNX is already dead at this point the `NWNX_POS` field never gets (re)added.
