### ISSUE TITLE
nwnx resource directory - possible to change it?

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#768]
Im wondering if it is possible to change via configuration the location of the nwnx resource directory.
Eg: the one that allows loading of external resources during runtime.

My setup at the moment is a VirtualBox Windows Host/ Linux Guest - 
I have my hak, tlk, override, module and sync directories hosted on the Windows host in a folder :
C:\NWServer\
These are then mounted in the guest as
/media/nwn

I've also got the DotNet assembly for the .Net Core plugin pointing to this share - but it seems there is no configuration setting for moving the  nwnx directory from the ./local/Neverwinter Nights directory.

Is this something that can presently be done or would it require re-work?

**Comment by Baaleos** [comment]
Note- there is a work around for this in that I can simply change the mount point - however given how flexible and configurable everything else is - I figured that the nwnx directory might be a folder that people may want to change the location of.

**Comment by Daztek** [comment]
I've been wanting to add an environment var for the path of the nwnx folder, but I've been lazy :D, I'll add it soon
