### ISSUE TITLE
Get/Set Faction Id - faction management

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#770]
In previous releases of nwnx (nwnx_cool or funcs I think) - I think there was Get/Set faction id - for npcs/objects.
I know that in EE there is a ChangeFaction method - which accepts two npc's as the arguments - but this does not help if you want to manage factions outside of the NWScript code base.
Eg: Create your own faction management system in say .Net Core etc.

Also - use of ChangeFaction forces people down the route of using the age old 'faction areas' where you have to keep a member of each faction alive in isolation (so they don't kill each other) - just so you have an object reference in order to interact with their faction.

`object oFirstFac = GetObjectByTag("vampire_faction");
object oTarget = ...;
ChangeFaction(oTarget,oFirstFac);
`

Where as you could just as easily :

`
NWNX_Factions_SetFaction(oTarget,nVampireFactionId);
`

Eg: You could store off the int for the vampire faction for use later, instead of the idea of having to constantly get the object for the npc's faction.

Im not sure if this would be as simple as exposing the m_nFactionId on the faction object itself, or if it would be safer to go through the internal methods etc

void AddMember(OBJECT_ID oidNewMemberID, BOOL bInPostProcess = false);
BOOL AttemptRemove(OBJECT_ID oidRemoveeID, OBJECT_ID oidRemoverID);

Eg: 
Remove from current faction,
Add to new faction.

Or would the Add method take care of the remove?

Note sure if this would be ideal as a new plugin or could just go into the Objects plugin - since factions exist at object level and above. (At least for placeables,npcs, triggers,encounters - not sure about sound,waypoints,items etc)

**Comment by Baaleos** [comment]
I can see that faction methods exist for encounters - perhaps it is simple matter of opening it up to encompass other classes?
```

ArgumentStack Encounter::SetFactionId(ArgumentStack&& args)
{
    if (auto *pEncounter = encounter(args))
    {
        auto factionId = Services::Events::ExtractArgument<int32_t>(args);

        ASSERT_OR_THROW(factionId >= 0);

        pEncounter->m_nFactionId = factionId;
    }
    return Services::Events::Arguments();
}
```

**Comment by GoLoT** [comment]
I took a look at `CNWSFaction::AddMember()` and this is what it seems to be doing:
* Checks that the oid belongs to a valid creature.
* Calls `CNWSFaction::RemoveMember()` to remove that creature from its current faction.
* If the creature is a player, it loops through all players in the new faction and updates hostility status (`CNWSCreature::SetPVPPlayerLikesMe()`).
* If `bInPostProcess == false` it calls `CNWSFaction::SendFactionUpdateAdd()` that AFAICT handles updating the party list.
* Checks that the creature doesn't belong to the faction already and if it doesn't, it's added.
* `CNWSCreature::BringAssociatesToNewFaction()` is called.
* If it's a player, `CNWSMessage::SendServerToPlayerParty_List()` is called.

What I gather from that is that setting `m_nFactionId` is not enough. The internal list in `CNWSFaction` has to be updated and in the case of players/familiars/henchmen the party list has to be updated too.

The function you propose should be easy to implement though, if anyone is up for it:

```
int nFactionId;
OBJECT_ID oidObject;
auto* pFaction = Globals::AppManager()->m_pServerExoApp->m_pcExoAppInternal->m_pFactionManager->GetFaction(nFactionId);
if (pFaction)
    pFaction->AddMember(oidObject);
```
