### ISSUE TITLE
Dynamic script database

### ISSUE THREAD

**Issue by navvator** [nwnxee/unified#782]
Hello! Do you allready adding support for dynamic script data?

**Comment by mtijanic** [comment]
I'm not understanding the question. If you mean if it is possible to modify the scripts while the game is running, then yes. You do not need NWNX for this. Just put your new .ncs file in the `development/` folder (or `nwnx/` folder if using nwnx) and the game will pick it up.

If this isn't what you meant, please provide some example of what was. Thanks.

**Comment by navvator** [comment]
It is i mean. Thank you!
