### ISSUE TITLE
Crash while running with dotNET

### ISSUE THREAD

**Issue by GideonCrawle** [nwnxee/unified#788]
Intermittent crash usually within 10-20 min of loading. Trying to replicate under more controlled conditions to see if caused by my scripts or not.

[nwserver-crash-1582194321.log](https://github.com/nwnxee/unified/files/4238491/nwserver-crash-1582194321.log)
[nwserver-crash-1582194323.log](https://github.com/nwnxee/unified/files/4238492/nwserver-crash-1582194323.log)
[nwserver-crash-1582194325.log](https://github.com/nwnxee/unified/files/4238493/nwserver-crash-1582194325.log)
[nwserver-crash-1582352853.log](https://github.com/nwnxee/unified/files/4238910/nwserver-crash-1582352853.log)

**Comment by mtijanic** [comment]
The first three are completely different from the last one. First three are happening at load time, and it would be really helpful if we had the logs to match them against. Seems like there's a fatal error and the error message would be printed.

The last one is purely a managed code crash. Possibly an unhandled NullReferenceException in a side thread?

**Comment by GideonCrawle** [comment]
Sorry, excuse my ignorance, but what other logs would be useful? The nwserver log?

**Comment by mtijanic** [comment]
The nwnx log would be most useful, especially if you have serverlogredirector turned on. This is the nwnx.txt file in logs dir, or your stdout.
if you don't have serverlogredirector, then nwnx.txt + nwserverlog.txt would be ideal.

Feel free to scrub them from any sensitive info, or send them to me via PM if you don't want them here.

**Comment by GideonCrawle** [comment]
This was resolved--the issue was the garbage collector eating the handlers because the container went out of scope.
