### ISSUE TITLE
nwnx_chat - Enable NWNX_Chat_SendMessage() to do per target message sending on channel NWNX_CHAT_CHANNEL_PLAYER_DM

### ISSUE THREAD

**Issue by Chimerik** [nwnxee/unified#791]
NWNX_Chat_SendMessage() is able to send message exclusively to a target on most channels, but not on NWNX_CHAT_CHANNEL_PLAYER_DM.

Would it be possible to enable this method to send message per target on this channel?

Thanks!

**Comment by WilliamDraco** [comment]
I anecdotally understand this also applies to NWNX_CHAT_CHANNEL_PLAYER_PARTY in the same way. Attempting to send a different message over party to two players results in both players receiving both messages.
