### ISSUE TITLE
Optimizations Plugin Returns Wrong Object when a Null String is passed to GetObjectByTag

### ISSUE THREAD

**Issue by Balanor** [nwnxee/unified#799]
1. Enable the optimizations plugin and the NWNX_OPTIMIZATIONS_OBJECT_TAG_LOOKUP env var.

2. Put this in a test module's OnEnter event, then launch server and login:
void main()
{
    vector vVec;
    location lLoc = Location(GetObjectByTag(""), vVec, 0.0); //Problem occurs when a null string is passed to GetObjectByTag (only when constructing a Location?)
    object oArea = GetAreaFromLocation(lLoc);
    //The following debug line will display the character's name on the first login. Subsequent logins work properly and display a null string. Takes a server reset to repro again
    SendMessageToPC(GetFirstPC(), "Area Name: "+GetName(oArea));
}

The expectation is GetName(oArea) should return a null string every time to indicate oArea is an invalid object. Instead, on the first PC login, it returns the PC name, indicating it is returning the entering object (PC) as oArea. As noted, this problem only seems to occur when a null string is passed to GetObjectByTag when constructing a location.

When the NWNX_OPTIMIZATIONS_OBJECT_TAG_LOOKUP env var is not enabled, the debug line in the above code always displays a null string/no name, even on the first PC login, as expected.

**Comment by Daztek** [comment]
I *think* it's because it also inserts PCs into the tag lookup list even though they usually don't have a tag, which means if you try to get a null string object tag you'll get the first PC without a tag that's online. 

The base game has an explicit `IsEmpty` check for the tag that returns OBJECT_INVALID, which the optimization does not.
