### ISSUE TITLE
Feature request: Dev Crit event

### ISSUE THREAD

**Issue by rybern** [nwnxee/unified#80]
There was an event for the pre-ee version of nwnx2 for Dev Crit. [Here's some documentation from that repo.](https://github.com/NWNX/nwnx2-linux/blob/d1b8c89049e964b81fbb664e1ab9cada1444b038/plugins/events/readme.txt)

It would help us out a lot if we could add this back in :)

**Comment by mtijanic** [comment]
This should be implemented as of #136

**Comment by rybern** [comment]
<3
