### ISSUE TITLE
nwnx_race plugin bug.

### ISSUE THREAD

**Issue by MhlChesnokov** [nwnxee/unified#808]
when i use in scripts itemproperty to weapons (seen in the screenshot) "ItemPropertyEnhancementBonusVsRace" (or any BonusVsRace properties), where VS is custom race is # 30 - the server crashes.
and all work correctly, when plugin nwnx_race is turn off.
only number of custom race # 30 - the server crashes .... 

I use the latest version of the server and plugins. (native)

[dump_log.txt](https://github.com/nwnxee/unified/files/4279318/dump_log.txt)
![unknown](https://user-images.githubusercontent.com/46106207/75744342-00fd6100-5d25-11ea-967e-04636d51206d.png)

**Comment by mtijanic** [comment]
This looks like you accidentally defined a loop in your race hierarchy. Like maybe race 30 is a child of itself or something. Can we see your 2da or code that defines this hierarchy?

**Comment by MhlChesnokov** [comment]
30 - just drow ... 
https://drive.google.com/open?id=1pUZNWOx6VsVhqBboYurWWoNi5O-r88Bd

**Comment by MhlChesnokov** [comment]
I figured out what the problem was. The problem was in my 2da "RacialModsTable" - the wrong RAСE parameter was set in the "RACEMOD_DROW" table. thx!
