### ISSUE TITLE
NWNX_SQL : Allow for non-standard ports 

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#812]
Use case: I have two docker/virtualbox instances
One is a QA server the other is live.

Live has mysql running on 3006, I would like QA mysql to run on 3307  

Due to some complexities that escape me - I am unable to get port forwarding to just route from 3307 to 3306 (host to guest) - to facilitate external to internal mysql connections to the QA server.

A possible work around would be for nwnx_sql to take property for the connection port.
Testing showed that 
127.0.0.1:3306 - did not work
but
127.0.0.1  does work

I think the way mysql connection strings work - is that they need the port specified as a 
PORT=3307;  argument.
It cannot be specified as hostname:3307  -because the internal mechanics of mysql connectors will put a 3306 as the port when the PORT connection string element is not included.
That would end up looking like:
127.0.0.1:3307:3306   - which is probably why it fails.

I think this can possibly be achieved by making a change to:

https://github.com/nwnxee/unified/blob/master/Plugins/SQL/Targets/MySQL.cpp#L37

**Comment by Daztek** [comment]
I'll add a config option for it tomorrowish
