### ISSUE TITLE
Exposing Tile Data

### ISSUE THREAD

**Issue by GideonCrawle** [nwnxee/unified#814]
After a discussion in the NWNX Discord it would be useful to have 

```string NWNX_Area_GetTileModel(object oArea, float fX, float fY);```

and other similar functions, in order to expose tile data from CNWTileData to scripts.

**Comment by Daztek** [comment]
Note: #816 exposed the tile model resref. Other data still needs to be exposed if needed.

**Comment by GideonCrawle** [comment]
Functionality desired has been added.
