### ISSUE TITLE
Possible bad interaction/bug with NWNX_Creature_SetOriginalName and NWNX_Rename

### ISSUE THREAD

**Issue by Wytchwood** [nwnxee/unified#815]
We've had consistent issues with characters' name not changing after initial alterations.

Reproduction steps:
Use NWNX_SetOriginalName() to change a player's name. Then add and remove an override; then try to change their name again. If they relog, their name will be back to whatever you changed it to the first time, no matter how many times you try to change it again. This occurred regardless of what PC it was tested on.

**Comment by Daztek** [comment]
Easiest would probably be to add a `NWNX_Rename_UpdateOriginalName()` function that updates the stuff in `m_RenameOriginalNames;`

**Comment by GideonCrawle** [comment]
Substantively, would that be simply reduplicating the functionality of NWNX_Creature_SetOriginalName()?
