### ISSUE TITLE
[MaxLevel] Max level reverted to 40

### ISSUE THREAD

**Issue by Gioz1979** [nwnxee/unified#821]
Server starts ok with nwnxee 8193.5 on Debian Buster 4.19.0-8-amd64; max level is set to 60 both on nwserver command line and in startup script exporting NWNX_MAXLEVEL_MAX.
I can connect to server and play, reaching level 45.
When I leave the game (and the server is empty as I am the only player, dunno if related) the server logs:

[NWNX_MaxLevel] [MaxLevel.cpp:110] No xp threshold set for level 42!. Max level reverted to 40.

The message doesn't lie as, if I join the server again, no "level up" interface is showing at all even if my character has enough xp to reach level 50.
In the server directory there are only NWNX_Core.so and the two required plugins, NWNX_ELC.so and NWNX_MaxLevel.so.

Here's my exptable.2da, however I already checked it twice and have it checked on discord too.
[exptable.2da.zip](https://github.com/nwnxee/unified/files/4328519/exptable.2da.zip)

Thanks,
Ivan

**Comment by lbadano** [comment]
I get exactly the same message for level 42, but I only get it when I'm shuting the server down

**Comment by Gioz1979** [comment]
Just tested if I can read values in game from the 2DA, so I edited the OnPlayerRest event with this script:

`void main()
{
    object oPC = GetLastPCRested();
    string row = Get2DAString("exptable", "XP", 40);
    SendMessageToPC(oPC, "exptable.2da row 40 (40->41) is " + row + " = " + IntToString(StringToInt(row)));
    row = Get2DAString("exptable", "XP", 41);
    SendMessageToPC(oPC, "exptable.2da row 41 (41->42) is " + row + " = " + IntToString(StringToInt(row)));
    row = Get2DAString("exptable", "XP", 42);
    SendMessageToPC(oPC, "exptable.2da row 42 (42->43) is " + row + " = " + IntToString(StringToInt(row)));
}`

and values are shown correctly.

**Comment by plenarius** [comment]
Did this issue go away or did you have to table it? Can you confirm how you use your 2da, is it in override? Part of a hak?

**Comment by Gioz1979** [comment]
Hello,
I didn't check it again since March, at the time I was just helping a friend but since then I've been pretty busy at work.

Regarding the test in my last comment: I remember that I used a simple custom hak with only one 2da - the exp table for levels 41-60. I have never installed any other haks and I was just helping about this topic, so I probably just imported the hak in the toolset and put the same hak in the 'hak' folder of the client too; both were running on my laptop under Linux, as detailed in the first comment.
I remember someone at the time talking about this issue, on the discord channel, probably being related with going from 32 to 64bit. Sorry can't remember who or other details.

I don't know if the issue went away, but I can arrange some tests during the weekend if it helps.

Thanks,
Ivan

**Comment by plenarius** [comment]
I'd appreciate if you could run some tests if you have the time, yes please. I'll be on Discord (I'm orth) if you want to relay info there. I can't replicate the issue myself though.

**Comment by Gioz1979** [comment]
Hey, sorry for the delay. My toolset wasn't starting up because of the infamous openal32.dll. I fixed that, then check my 'training' module (simple testing module, good for going over 40 quickly). Uploaded to a small server of mine, but nwserver doesn't start telling me that module training wasn't found (nwsync seems ok though).
I'll work on it during the next few days, I'll let you know: sorry for being unable to bring some news at the table but I'm pretty busy at work during these days.

Ivan
