### ISSUE TITLE
[Feature Request] Passive Saving Throw Bonus

### ISSUE THREAD

**Issue by Aschent89** [nwnxee/unified#822]
Similar to Skillranks being impacted by Feats passively, Saving Throws would also be a helpful additions for Feats.

Example:

Feat: Bravery
Provides +2 Bonus to Fear Saving Throws.

**Comment by mtijanic** [comment]
Can't you just check OnLevelUp if the feat is acquired and use `NWNX_Creature_SetBaseSavingThrow()` to add the bonus. Then undo the bonus OnLevelDown if it is lost.

**Comment by Aschent89** [comment]
I forgot to circle back here.

Based on the details for `NWNX_Creature_SetBaseSavingThrow()`, this is specific to Will, Fort & Reflex. Is that not the case? If I can use the `SAVING_THROW_TYPE_X`, that would work instead.

```
/// @brief Sets the creature's base save.
/// @param creature The creature object.
/// @param which One of SAVING_THROW_FORT, SAVING_THROW_REFLEX or SAVING_THROW_WILL
/// @param value The base save value.
```

**Comment by mtijanic** [comment]
When you're not sure how a given function works, you can just check in the source. They're quite easy to find.. If it's NWNX_Creature, it's in Plugins/Creature/Creature.cpp, and the names usually match 1:1 between cpp and nss:

https://github.com/nwnxee/unified/blob/master/Plugins/Creature/Creature.cpp#L1456-L1485

**Comment by jd28** [comment]
That's not what they want @mtijanic, they want save modifiers vs a specific subtype.

**Comment by Aschent89** [comment]
@jd28 is correct, I am looking for subtypes. An effect works just fine, however the nwnx-style of implementation is cleaner.
