### ISSUE TITLE
Retrieve adding/removing object for NWNX_ON_INVENTORY_ADD/REMOVE events

### ISSUE THREAD

**Issue by rinehardt** [nwnxee/unified#826]
I've been experimenting with these events:
```    ## Container Change Events
    - NWNX_ON_INVENTORY_ADD_ITEM_BEFORE
    - NWNX_ON_INVENTORY_ADD_ITEM_AFTER
    - NWNX_ON_INVENTORY_REMOVE_ITEM_BEFORE
    - NWNX_ON_INVENTORY_REMOVE_ITEM_AFTER

    @note NWNX_ON_INVENTORY_REMOVE_ITEM_* is not skippable

    'OBJECT_SELF' = The container

    Event Data Tag        | Type   | Notes
    ----------------------|--------|-------
    ITEM                  | object | Convert to object with NWNX_Object_StringToObject()
```

And I was wondering if it would be possible to have the object that has added or removed the item in addition to the 'ITEM' parameter. It would make the events far more useful.

**Comment by Daztek** [comment]
Does `GetItemPossessor(NWNX_Object_StringToObject(NWNX_Events_GetEventData("ITEM")));` in the _BEFORE event return anything useful?

**Comment by rinehardt** [comment]
Ah, that does seem to work. I thought I had already tried that function, but I was using the wrong one. Thanks.
