### ISSUE TITLE
Adding duration variable to NWNX_Player_ApplyLoopingVisualEffectToObject

### ISSUE THREAD

**Issue by FrogsOfDoom** [nwnxee/unified#847]
As the title implies, I think, if feasible, it would be a good idea to add a duration to this NwNx function since otherwise it needs to be removed manually.

void NWNX_Player_ApplyLoopingVisualEffectToObject(object player, object target, int visualeffect)

Thanks!

**Comment by plenarius** [comment]
As discussed in #1131, it's better if you just do something like below

```c
void ApplyLoopingVisualEffectToObjectDuration(object oPC, object oObject, int vfx, float fDuration)
{
    NWNX_Player_ApplyLoopingVisualEffectToObject(oPC, oObject, vfx);
    DelayCommand(fDuration, NWNX_Player_ApplyLoopingVisualEffectToObject(oPC, oObject, vfx));
}
```
