### ISSUE TITLE
Constants missing in Constants.hpp

### ISSUE THREAD

**Issue by BhaalM** [nwnxee/unified#85]
```
int ITEM_APPR_TYPE_SIMPLE_MODEL         = 0;
int ITEM_APPR_TYPE_WEAPON_COLOR         = 1;
int ITEM_APPR_TYPE_WEAPON_MODEL         = 2;
int ITEM_APPR_TYPE_ARMOR_MODEL          = 3;
int ITEM_APPR_TYPE_ARMOR_COLOR          = 4;
int ITEM_APPR_NUM_TYPES                 = 5;
```

I can add theem myself, but I don't know if I'm allowed to do it

**Comment by Liareth** [comment]
The constants file was just taken from NWNX2 (for 1.69) and not checked for accuracy, so it's expected that some things will be wrong, guessed, or missing. Feel free to submit a PR to add these if you'd like!

**Comment by BhaalM** [comment]
Ok, I'll do it.
