### ISSUE TITLE
[nwnx_player] NWNX_Player_SetPlaceableNameOverride does not rewrite the name

### ISSUE THREAD

**Issue by LiarisFreeze** [nwnxee/unified#859]
NWNX_Player_SetPlaceableNameOverride does not rewrite the name.
Nothing happens at all.

Please fix it. ( T__T )

**Comment by Daztek** [comment]
I think it still works if you re-enter the area. 

Dunno if it can be made to update on the fly. Probably needs some trickery with `int32_t m_nUpdateDisplayNameSeq;`
