### ISSUE TITLE
Crash backtrace

### ISSUE THREAD

**Issue by BhaalM** [nwnxee/unified#862]
Just in case you find something useful from this backtrace:

=== Backtrace
./nwserver-linux(+0x4eaa46)[0x5575a1a9aa46]
./nwserver-linux(+0x4ea1e1)[0x5575a1a9a1e1]
./nwserver-linux(+0x4eaae1)[0x5575a1a9aae1]
./NWNX_Core.so(nwnx_signal_handler+0xc1)[0x7fcaf1894e71]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7fcaf0478f20]
./nwserver-linux(+0x2f7f41)[0x5575a18a7f41]
/nwn/server8193_9/bin/linux-x86/NWNX_WebHook.so(+0x1964f)[0x7fcae9f2264f]
./NWNX_Core.so(_ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt8functionIFvvEES
aIiESC_E6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data+0x39)[0x7fcaf18f2f79]
./NWNX_Core.so(_ZNSt13__future_base13_State_baseV29_M_do_setEPSt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEPb+0x2e)[0x7fcaf18f31de]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf827)[0x7fcaf13d4827]
./NWNX_Core.so(_ZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_+0x75)[0x7fcaf
18f3cd5]
./NWNX_Core.so(_ZN7NWNXLib8Services5Tasks11ProcessWorkERSt6vectorISt13packaged_taskIFvvEESaIS5_EERSt5mutex+0x1a6)[0x7fcaf18eea66]
./NWNX_Core.so(_ZN7NWNXLib8Services10TasksProxyD2Ev+0x42)[0x7fcaf18f0b32]
./NWNX_Core.so(_ZN4Core8NWNXCore13UnloadPluginsEv+0x154)[0x7fcaf18972b4]
./NWNX_Core.so(_ZN4Core8NWNXCore8ShutdownEv+0x11)[0x7fcaf18973e1]
./NWNX_Core.so(_ZN4Core8NWNXCore20DestroyServerHandlerEP11CAppManager+0xe1)[0x7fcaf18977f1]
./nwserver-linux(+0xcde8d)[0x5575a167de8d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fcaf045bb97]
./nwserver-linux(_start+0x29)[0x5575a1680e79]

**Comment by mtijanic** [comment]
Full log would help. Or at least to say which version this is from, since it's not latest.

**Comment by BhaalM** [comment]
Sorry, I forgot to say its 8193.9

**Comment by Daztek** [comment]
Looks like a Webhook message trying to queue things on the main thread after nwserver has been killed but before nwnx shuts down

**Comment by mtijanic** [comment]
Probably a response from server that wants to trigger an event.

**Comment by BhaalM** [comment]
To be clear, it only happened once so it's really not a problem for me, but I thought the crash could be useful.
