### ISSUE TITLE
[FEATURE REQUEST] Expose event quick bar slot modification

### ISSUE THREAD

**Issue by Chimerik** [nwnxee/unified#869]
Hello,

Being able to catch the event of a PC changing one of his quick bar slots would help improve systems using the qbs as a menu.

If someone with enough skills could add this feature someday, it would be great.

Thanks a lot!

**Comment by Daztek** [comment]
Hooking `BOOL CNWSMessage::HandlePlayerToServerGuiQuickbar_SetButton(CNWSPlayer * pPlayer, uint8_t nButton, uint8_t nObjectType);` would probably work for this.
