### ISSUE TITLE
[BUG] NWNX_SkillRanks plugin enabled breaks correct reading values from ruleset.2da

### ISSUE THREAD

**Issue by silent-rock** [nwnxee/unified#886]
NWN: 8193.12
NWNX: latest release for 8193.12

I've changed the value for `SKILL_FOCUS_SKILL_BONUS` in ruleset.2da. Using it serverside in haks. Hak file has top priority, no conflicts with other hak files, other changes in ruleset.2da work fine.

With `NWNX_SkillRanks` enabled it resets the value set in ruleset.2da and reads the default (3 for skill focus). Disabling the plugin fixes the issue. I'm not using any function from this plugin at the moment.

NWNX_SkillRanks plugin, when enabled, shouldn't interfere with ruleset.2da changes. It should overwrite ruleset.2da values only when proper functions are called on module load.

**Comment by Daztek** [comment]
Do you call `NWNX_SkillRanks_SetSkillFeatFocusModifier()` anywhere in your module?

**Comment by silent-rock** [comment]
@Daztek Nope, I'm not. Searched for that through all the module scripts.

**Comment by Daztek** [comment]
Okay, repro'd it, not sure why SkillRanks is messing it up tho. Might be trying to get values before ruleset.2da is loaded

**Comment by Daztek** [comment]
Yep, it hooks `CNWRules::LoadSkillInfo();` to do its skill stuff, but `CNWRules::LoadRulesetInfo();` runs after it. Which means it cannot find the value in ruleset.2da and uses the default value.
