### ISSUE TITLE
[weapon] Potential nullptr deref

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#893]
https://github.com/nwnxee/unified/blob/69b20ca3d6f046c6fd2756a3525e2d950e3c66e1/Plugins/Weapon/Weapon.cpp#L612-L651

If the weapon is null, base item gloves are used.  If a creature has a devcrit feat for gloves and the server sets a devcrit event script there will be a nulllptr dereference at line 636.  I'm too rusty on NWN internals to fix this and not even sure what's best (if anything) given it would likely be a very rare occurrence.

**Comment by GoLoT** [comment]
Maybe change it to `plugin.m_DCData.oidWeapon = pWeapon ? pWeapon->m_idSelf : Constants::OBJECT_INVALID;` and let the user deal with it.

Optionally adding `pWeapon = pStats->m_pBaseCreature->m_pInventory->GetItemInSlot(Constants::EquipmentSlot::Arms);` to `if (pWeapon == nullptr)` to return the gloves/bracer item if any.
