### ISSUE TITLE
[docs] Suggestion for quick start guides

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#894]
Add a folder with quick start guides (or maybe the Github wiki?).  Say maybe "Quick Intro to Ghidra & NWNX".  I can never remember how to set the base address so that the functions match up.  I don't know if that one would acceptable to Beamdog tho.

Maybe a "My First NWNX Plugin" just something basic.  Really the best option for getting started seems to just be copy & paste from another plugin.

Stuff like that.  I'm sure there's tons of valuable info floating around in the Discord too.

**Comment by mtijanic** [comment]
I'll always accept more documentation, but that part is lowest priority IMO. Should first focus on guides to set up NWNX for a PW, possibly a 1.69 migration guide. Then guides on how to write plugins using just the API (like e.g. https://github.com/BhaalM/stuff/blob/master/simple_nwnxee_tutorial.md ), etc.

There is probably only a couple people who would pick up Ghidra and go down that rabbit hole, and the live chat support is probably good enough for them.

**Comment by jd28** [comment]
That's true.  I hadn't ever seen Bhaal's guide, that's a very nice intro!

**Comment by mtijanic** [comment]
Imma close this as the guide is linked in the new awesome-nwnx. "More docs" is an ever present request and anyone is always welcome to PR links to documentation, does not need an open issue for it
