### ISSUE TITLE
JVM: nwnx_jvm_token wrong?

### ISSUE THREAD

**Issue by Liareth** [nwnxee/unified#9]
I noticed that nwnx_jvm_token.nss:5 and nwnx_jvm_token.nss:6 push an argument for the Event function but then call the Token function. I don't fully understand what this function does nor do I have the knowledge or setup to test it, but this seems wrong to me. It looks like every time call_token is called, 2 more arguments get pushed onto the Event stack, and Token gets called with nothing. Can someone (@niv @zunath) who knows about JVM investigate when you get a chance?

**Comment by zunath** [comment]
I'm not sure about this one. Will have to yield to @niv ...

**Comment by mtijanic** [comment]
WNF. JVM is a goner.
