### ISSUE TITLE
PostgreSQL compilation issue

### ISSUE THREAD

**Issue by ELadner** [nwnxee/unified#90]
Something in commit 9f45d71 broke finding the libpq includes and libraries on my system.  Not sure where to start but find_packge isn't finding PostgreSQL for some reason.

**Comment by Liareth** [comment]
@kmsheehan Do you know anything about this?

**Comment by ELadner** [comment]
On closer inspection, I think it's just a CMake warning or something.

This is printed during the makefile build stage:

```
-- Found JNI: /usr/lib/jvm/java-9-oracle/lib/libjawt.so  
-- Found Java: /usr/lib/jvm/java-9-oracle/bin/java (found version "9.0.4") 
-- Found Ruby: /home/eladner/.rvm/rubies/ruby-2.4.2/bin/ruby (found version "2.4.2") 
CMake Warning at Plugins/SQL/CMakeLists.txt:11 (message):
  Not compiling with MYSQL support, not found


CMake Warning at Plugins/SQL/CMakeLists.txt:23 (message):
  Not compiling with PostgreSQL support, not found


-- Configuring done
-- Generating done
```

But during the compile stage, it does correctly build the NWNX_SQL.so binary.

**Comment by Liareth** [comment]
It can build NWNX_SQL even if it has no targets - it will just throw an exception on startup because it has no targets ...

**Comment by mtijanic** [comment]
Incidentally, I'm a big fan of SQLite. Is there interest for embedding it in NWNX?

**Comment by kmsheehan** [comment]
I would think it should be on the list of things to do - if NWNX is enabled for SP / MP and not just PWs it is much easier (no real setup) to run with an embedded DB.

**Comment by ELadner** [comment]
I like SQLite as well, but it's not a good fit for a multi-user environment like PW servers.  It's lack of ACID support pretty much kills that.

**Comment by ELadner** [comment]
After thinking about it, you could probably do SQLite now, but if you ever move to multi-threaded, you'd probably start to have issues.

**Comment by mtijanic** [comment]
NWScript is never going to be multithreaded. But when we add async SQL query support, SQLite will be ill equipped to handle it.
The big issue with SQLite is that it'll be hard to expose the same database to other services, such as a webserver. But I think that's a very PW specific usecase, and as glowinger says, sqlite would be great for regular MP modules using NWNX.

**Comment by mtijanic** [comment]
There's nothing to be done here. Incidentally, SQLite support was also recently added as mentioned here. Closing.
