### ISSUE TITLE
Server crash in 8193.13

### ISSUE THREAD

**Issue by vaardu** [nwnxee/unified#907]
Had the following come out from docker backtrace after crash just 10 minutes before or so.
I once more can't say much anything myself, except that it indicates we may have something wrong there somewhere, which I am not aware of.

Any idea if this is something that's a fault on our side would be great.

[docker_backtrace_16_05_2020.txt](https://github.com/nwnxee/unified/files/4638293/docker_backtrace_16_05_2020.txt)

**Comment by vaardu** [comment]
Received another crash and saw another:
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

I am not sure what this is about.

[docker_backtrace_19_05_2020.txt](https://github.com/nwnxee/unified/files/4647013/docker_backtrace_19_05_2020.txt)

**Comment by GoLoT** [comment]
That last one is the same as **crast_21_4_2020_c.txt** in #864 . I have no idea why it's crashing but it seems to be isolated to your server. I haven't seen similar reports anywhere and it's oddly specific to that variable (`CNWSCombatData::m_sDamageDebugText`).

I'd say it will be impossible to track it down without enough context and a way to reproduce and debug, but at this point I'm fairly certain that it's something on your end. Sadly I can't offer any advice on how to proceed.

**Comment by GoLoT** [comment]
I made a mistake reading the crash log. After checking it with @mtijanic the crash is happening when trying to `CNWSCombatData::m_alstOnHitGameEffects`.

Can't really say why that pointer isn't valid. It's possible that it is a dangling pointer.

**Comment by vaardu** [comment]
I had couple more from the latest report, and I'll keep bringing them in at times. Perhaps someone might get an idea as it seems these are something more deeper than what my ability can reach. Maybe it might give ideas to someone at some point.

[docker_backtrace_19_05_2020B.txt](https://github.com/nwnxee/unified/files/4652193/docker_backtrace_19_05_2020B.txt)

[docker_backtrace_19_05_2020C.txt](https://github.com/nwnxee/unified/files/4652192/docker_backtrace_19_05_2020C.txt)

**Comment by mtijanic** [comment]
Unfortunately it's almost impossible to debug from these stack traces. The bug happened at some random point before the crash and corrupted the heap. The crash is then virtually inevitable, but not immediate. So the stacktrace is useless.

It would really help to find the cause of the crash, by making a smaller repro module. Or maybe you'd be willing to run the module natively with ASAN?

**Comment by vaardu** [comment]
I wish I could easily reproduce the issue, but it is truly random as it has happened with few hours uptime, and happened with 24-30 hours uptime. If I had any slight idea of what to look at, I could try to engage some debug log levels or something else as an option. 

I am not really sure of the native running, but I will take a look at it and what it would require, these have been less my field over the years and only recently have I gotten into it more and done it mostly through docker. I'll discuss with more capable member of the team in regards the server aspects and see the possibility about native running.

**Comment by faustofjunqueira** [comment]
Hi, I had the same crash in my case.

```
nwserver_1  | I [05:32:28] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:75] (Server) Query: select id, val, expire, player, tag, name from pwdata where player=$1 and tag=$2 and name=$3
nwserver_1  | D [05:32:28] [NWNX_Core] [Events.inl:9] Pushing argument 'theodordemolition'. Event 'PreparedString', Plugin: 'NWNX_SQL'.
nwserver_1  | D [05:32:28] [NWNX_Core] [Events.inl:9] Pushing argument '0'. Event 'PreparedString', Plugin: 'NWNX_SQL'.
nwserver_1  | D [05:32:28] [NWNXLib] [Events.cpp:35] Calling event handler. Event 'PreparedString', Plugin: 'NWNX_SQL'.
nwserver_1  | D [05:32:28] [NWNX_SQL] [PostgreSQL.cpp:236] Assigning position 0 to value 'theodordemolition'
nwserver_1  |  NWNX Signal Handler:
nwserver_1  | ==============================================================
nwserver_1  |  NWNX has crashed. Fatal error: Segmentation fault (11).
nwserver_1  |  Please file a bug at https://github.com/nwnxee/unified/issues
nwserver_1  | ==============================================================
nwserver_1  | E [05:32:28] [NWNXLib] [Events.cpp:42] Plugin 'NWNX_SQL' failed event 'PreparedString'. Error: basic_string::_M_construct null not valid
nwserver_1  | I [05:32:28] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:75] (Server) player: theodordemolition
nwserver_1  | D [05:32:28] [NWNX_Core] [Events.inl:9] Pushing argument '~'. Event 'PreparedString', Plugin: 'NWNX_SQL'.
nwserver_1  | D [05:32:28] [NWNX_Core] [Events.inl:9] Pushing argument '1'. Event 'PreparedString', Plugin: 'NWNX_SQL'.
nwserver_1  | D [05:32:28] [NWNXLib] [Events.cpp:35] Calling event handler. Event 'PreparedString', Plugin: 'NWNX_SQL'.
nwserver_1  | D [05:32:28] [NWNX_SQL] [PostgreSQL.cpp:236] Assigning position 1 to value '~'
```

My desktop info: 
 - Windows 10 Profissional
- Docker Desktop
- docker compose

```yaml
version: "3.8"
services:
  db:
    image: postgres:12.2-alpine
    restart: unless-stopped
    env_file: ${PWD-.}/config/postgres.env
    ports: 
      - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data
  nwserver:
    depends_on: 
      - db
    image: nwnxee/unified:build8193.12
    stdin_open: true
    tty: true
    env_file: ${PWD-.}/config/nwserver.env
    volumes:
    - ${PWD-.}/volumes/logs:/nwn/run/logs.0
    - ${PWD-.}/volumes/server/:/nwn/home
    restart: unless-stopped
    ports:
    - "5121:5121/udp"
volumes:
  postgres:
```
nwserver.env
```
# Database
NWNX_SQL_TYPE=POSTGRESQL
NWNX_SQL_HOST=db
NWNX_SQL_PORT=5432
NWNX_SQL_USERNAME=lod-nw3-admin
NWNX_SQL_PASSWORD=my-lod-4-theodor-M4sT3r
NWNX_SQL_DATABASE=lod
#NWNX_SQL_QUERY_METRICS=true

# NWNX Server
NWNX_CORE_LOG_LEVEL=5
NWNX_CORE_SQL_LEVEL=7
NWNX_MAXLEVEL_MAX=60

# NW Server
NWN_PORT=5121
NWN_MODULE=LOD-EE
NWN_SERVERNAME=Lod - Legend of Destiny
NWN_PUBLICSERVER=1
NWN_MAXHITPOINTS=1
NWN_MAXCLIENTS=96
NWN_MINLEVEL=1
NWN_MAXLEVEL=60
NWN_PAUSEANDPLAY=1
NWN_PVP=2
NWN_SERVERVAULT=1
NWN_ELC=0
NWN_ILR=0
NWN_GAMETYPE=0
NWN_ONEPARTY=0
NWN_DIFFICULTY=3
NWN_AUTOSAVEINTERVAL=0
NWN_RELOADWHENEMPTY=0
NWN_PLAYERPASSWORD=
NWN_DMPASSWORD=gatinhalinda
NWN_ADMINPASSWORD=gatinhalinda
NWN_NWSYNCURL=
NWN_NWSYNCHASH=

# NWNX Library
NWNX_CHAT_SKIP=n
NWNX_CORE_SKIP=n
NWNX_CREATURE_SKIP=n
NWNX_ELC_SKIP=n
NWNX_MAXLEVEL_SKIP=n
NWNX_RACE_SKIP=n 
NWNX_SKILLRANKS_SKIP=n
NWNX_SQL_SKIP=n 
NWNX_UTIL_SKIP=n
# NWNX_SERVERLOGREDIRECTOR_SKIP=y
# NWNX_ADMINISTRATION_SKIP=y
# NWNX_BEHAVIOURTREE_SKIP=y
# NWNX_DATA_SKIP=y
# NWNX_EVENTS_SKIP=y
# NWNX_JVM_SKIP=y
# NWNX_METRICS_INFLUXDB_SKIP=y
# NWNX_OBJECT_SKIP=y
# NWNX_PLAYER_SKIP=y
# NWNX_PROFILER_SKIP=y
# NWNX_REDIS_SKIP=y 
# NWNX_RUBY_SKIP=y 
# NWNX_THREADWATCHDOG_SKIP=y 
# NWNX_TIME_SKIP=y 
# NWNX_TRACKING_SKIP=y
```

**Comment by plenarius** [comment]
Admin has confirmed this is no longer an issue in Discord, closing for cleanliness. https://discord.com/channels/382306806866771978/382914210176172032/965304860620763206
