### ISSUE TITLE
NWNX Compilation error

### ISSUE THREAD

**Issue by navvator** [nwnxee/unified#911]
Hello! I try compile nwnx as 
CC=gcc-7 CXX=g++-7 cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../
and get error:
CMake Warning at Plugins/SQL/CMakeLists.txt:12 (message):
  Not compiling with MYSQL support, not found

CMake Warning at Plugins/SQL/CMakeLists.txt:21 (message):
  Not compiling with PostgreSQL support, not found

CMake Warning at Plugins/SQL/CMakeLists.txt:30 (message):
  Not compiling with SQLite3 support, not found

I have Ubuntu 18 and MYSQL Ver 14.14 Distrib 5.7.30, for Linux (x86_64)

Can you help me?

**Comment by mtijanic** [comment]
That's not necessarily an error, just that you can't build the SQL plugin. You need to install dependencies for your database of choice. For example, for sqlite3 you need to run
```
apt install sqlite3 libsqlite3-dev
```

For mysql, it should be
```
apt install libmysqlclient20 libmysqlclient-dev
```

**Comment by navvator** [comment]
THank you a lot!
