### ISSUE TITLE
[Bug] Greater Weapon Focus - Two-sided weapons

### ISSUE THREAD

**Issue by FrogsOfDoom** [nwnxee/unified#938]
When applying Greater Weapon Focus on a two-bladed weapon (ie: Dire Mace, Double Scimitar, etc.), the +1 attack bonus is only granted on the main-hand attack:

![image](https://user-images.githubusercontent.com/51026560/84572272-e2b4f180-ad66-11ea-9469-5902e7d15099.png)

This character has Ambidextery, Two-Weapon Fighting and Improved Two-Weapon Fighting so the difference between the main-hand attack and the off-hand attack should be 4, but it's 5. I tested attacking to confirm it's not just a character sheet bug, but getting the same results.

**Comment by GoLoT** [comment]
I don't see the offhand info in that screenshot. If you are referring to the +14/+9, that's 2 main hand attacks with fighter progression (-5AB per attack). The offhand attack is should be displayed below as a different set of attacks.

**Comment by FrogsOfDoom** [comment]
> I don't see the offhand info in that screenshot. If you are referring to the +14/+9, that's 2 main hand attacks with fighter progression (-5AB per attack). The offhand attack should be displayed below as a different set of attacks.

Ah yeah, sorry, here's a better screenshot:

![image](https://user-images.githubusercontent.com/51026560/84594077-bdcf8580-ae1d-11ea-8438-9f1968de140a.png)

Both the main and off-hand attack should have the same AB but you can see the difference.
