### ISSUE TITLE
[Docs] Incorrect docs in comment of NWNX_ON_VALIDATE_ITEM_EQUIP_*

### ISSUE THREAD

**Issue by weavejester** [nwnxee/unified#957]
The tag for the variable should be `ITEM_OBJECT_ID` instead of `ITEM`:

https://github.com/nwnxee/unified/blob/87f1663d110c013b6e34b19cae2ef15922b709ac/Plugins/Events/NWScript/nwnx_events.nss#L127

**Comment by mtijanic** [comment]
Fixed in 0d65c36befa04c0cc320de16a1b1d0d340e796ee

(was it really easier to open a bug then just fix through github web editor? :stuck_out_tongue: )

**Comment by weavejester** [comment]
I completely forgot GitHub has a web editor 😃
