### ISSUE TITLE
request: GetObjectAILevel() SetObjectAILevel()

### ISSUE THREAD

**Issue by shadguy** [nwnxee/unified#960]
Per subject line; specifically interested in placeables.  Background info from Discord chatter is pasted below.
---

From Discord:

Shadooow: Placeables tend to fire the spell with a delay in large modules. But maybe I can just time the delay and hope it will be consistent.

clippy: Oh, I think that's just their VERY_LOW AI, try SetObjectAILevel() a higher level on it temporarily and then fire the spell

shadguy:  I see a SetAILevel() command with comments about creatures, but not SetObjectAILevel();  it sounds worth trying the former on placeables regardless, from your comment.

clippy: That's the one I meant. I think it works on placeables.  If not, something nwnx can easily add

shadguy: Thanks - I've got some respawning traps that didnt get deployed much because they basically stop performing after respawn - will try this weekend.  Sounds strongly related to Shadooow's comment, thanks for the proposed solution :slight_smile:

Daz: SetAILevel() only works on non player creatures

**Comment by Daztek** [comment]
Resolved by #1224
