### ISSUE TITLE
[Feature Request] Adjust Effect Durations Without Removing Effect

### ISSUE THREAD

**Issue by Tildryn** [nwnxee/unified#963]
Currently there's no way to extend or reduce an effect's duration without removing it and recreating the effect entirely, then reapplying it. One can't even just store the effect to a variable and reapply it with a new duration, since the RemoveEffect just removes that effect as well (presumably because it uses the ID to remove it). Removing the effect also ends up triggering events related to effect removal in the Events plugin, which means any other code related to it requires workarounds to avoid executing anything related to the given effect being removed.

It would be ideal to be able to adjust an effect's duration without removing and reconstructing it from scratch. This also allows more generic control of extending or reducing effect durations, instead of requiring bespoke reconstruction of an effect to reapply it with a new duration.

**Comment by mtijanic** [comment]
I'm thinking `NWNX_Effect_ReplaceEffect(effect eOld, effect eNew)`. So you:

1. iterate over all effects on object, searching for the one you want (e.g. by tag)
2. unpack that effect (`NWNX_Effect_UnpackEffect()`)
3. modify the duration
4. repack it (`NWNX_Effect_PackEffect()`)
5. call `NWNX_Effect_ReplaceEffect()` to replace the old one with the new

**Comment by Tildryn** [comment]
That seems like it could work pretty great, and be more flexible as well. Would that work okay with linked effects as well? I'm not sure how linked effects determine these things exactly.

**Comment by mtijanic** [comment]
It should work with linked effects, so long as you're only changing the non-link related stuff. If you attempt to unlink/relink effects after they are applied, god knows what would happen.

**Comment by Tildryn** [comment]
Sounds pretty perfect. This may be going beyond the scope of this change and into things that I'd need to experiment with myself, but off the cuff do you happen to know which of the fields of fDuration, nExpiryCalendarDay, and nExpiryTimeOfDay one would have to change? Just the fDuration, or all three? And if one has to change this on all the linked effects or just the first one of the linked list?

**Comment by mtijanic** [comment]
Without looking into it, I think the expiry day/time. I'm not sure about linked effects.

When you iterate over effects with Get{First,Next}Effect, does it return each individual linked effect, or is it only one?

**Comment by Tildryn** [comment]
When you iterate with Get{First,Next}Effect, it returns each individual linked effect.

**Comment by mtijanic** [comment]
Then I'm 90% sure you'd need to correct the times for each individual linked effect. :shrug:

**Comment by Daztek** [comment]
Calling `CGameEffect::UpdateLinked` on the replaced effect should update the expiry day/time and duration for the linked effects.
