### ISSUE TITLE
[Feature Request] Add support for blocking store transactions from taking place (buying, selling items to stores)

### ISSUE THREAD

**Issue by torradmin** [nwnxee/unified#991]
It would be nice to be able to stop a store transaction from happening. Right now it's kind of hard to limit different kinds of items with same base item type from being sold to stores and dealing with items after the fact is kind of messy. Also there's the issue of selling unidentified items to stores making them identified.

**Comment by mtijanic** [comment]
Should be just a matter of hooking these two from CNWSCreature into StoreEvents
```C
    BOOL RequestBuy(OBJECT_ID oidItemToBuy, OBJECT_ID oidStore, OBJECT_ID oidDesiredRepository = 0x7f000000);
    BOOL RequestSell(OBJECT_ID oidItemToSell, OBJECT_ID oidStore);
```
